openapi: 3.2.0
info:
  description: '## Overview


    This application offers an API for managing assignments and tasks.'
  title: assignments Label API
  contact: {}
  version: 2.36.5
tags:
- name: Label
paths:
  /api/v1/label:
    get:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      tags:
      - Label
      summary: Look up labels
      parameters:
      - description: Workorder ID for which labels should be returned
        name: workorderId
        in: query
        schema:
          type: integer
      - description: Task ID for which labels should be returned
        name: taskId
        in: query
        schema:
          type: integer
      - description: Label type
        name: labelType
        in: query
        required: true
        schema:
          type: string
      - description: If total matching record count should be return in response header
        name: withTotalCount
        in: query
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LabelResponse'
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: getApiV1Label
      x-operation-id-source: derived
    put:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      tags:
      - Label
      summary: Set multiple labels on the same object.
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LabelResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelBulkRequest'
        description: Labels to set
        required: true
      operationId: putApiV1Label
      x-operation-id-source: derived
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      tags:
      - Label
      summary: Add a new label record
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelRequest'
        description: Label record
        required: true
      operationId: postApiV1Label
      x-operation-id-source: derived
    delete:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      tags:
      - Label
      summary: Delete one label record
      parameters:
      - description: Workorder ID
        name: workorderId
        in: query
        schema:
          type: integer
      - description: Task ID
        name: taskId
        in: query
        schema:
          type: integer
      - description: Label type
        name: labelType
        in: query
        required: true
        schema:
          type: string
      - description: Label code
        name: label
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: deleteApiV1Label
      x-operation-id-source: derived
components:
  schemas:
    LabelRequest:
      type: object
      properties:
        label:
          type: string
        labelType:
          type: string
        taskId:
          type: integer
        workorderId:
          type: integer
    LabelResponse:
      type: object
      properties:
        createdAt:
          type: string
        createdById:
          type: integer
        label:
          type: string
        labelType:
          type: string
        taskId:
          type: integer
        workorderId:
          type: integer
    LabelBulkRequest:
      type: object
      properties:
        labelType:
          type: string
        labels:
          type: array
          items:
            type: string
        taskId:
          type: integer
        workorderId:
          type: integer
  securitySchemes:
    AccessToken:
      type: apiKey
      name: accessToken
      in: header
    ErplyClientCode:
      type: apiKey
      name: clientCode
      in: header
    ErplyJWT:
      type: apiKey
      name: jwt
      in: header
    ErplySession:
      type: apiKey
      name: sessionKey
      in: header
    RequestKey:
      type: apiKey
      name: requestKey
      in: header
