openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM Parameter Set to Group Linking API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: Parameter Set to Group Linking
paths:
  /v1/product/parameter/set/groups/{ids}:
    delete:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Parameter Set to Group Linking
      summary: Delete Linked Groups
      parameters:
      - description: up to 100 semicolon delimited link IDs
        name: ids
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: deleteV1ProductParameterSetGroupsByIds
      x-operation-id-source: derived
  /v1/product/parameter/set/{id}/groups:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Parameter Set to Group Linking
      summary: Get Linked Groups
      parameters:
      - description: set ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      - description: skip n records
        name: skip
        in: query
        schema:
          type: integer
      - description: amount to take
        name: take
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/models.SetToGroupResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: getV1ProductParameterSetByIdGroups
      x-operation-id-source: derived
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Parameter Set to Group Linking
      summary: Link Group
      parameters:
      - description: set ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '304':
          description: Not Modified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requests.IDRequest'
        description: group ID
        required: true
      operationId: postV1ProductParameterSetByIdGroups
      x-operation-id-source: derived
components:
  schemas:
    responses.Response:
      type: object
      properties:
        id:
          type: integer
          example: 73
    models.SetToGroupResponse:
      type: object
      properties:
        added:
          description: Unix timestamp
          type: integer
          example: 1595230999
        addedby_id:
          description: user ID
          type: integer
          example: 1
        changed:
          description: Unix timestamp
          type: integer
          example: 1595230999
        changedby_id:
          description: user ID
          type: integer
          example: 1
        dataset_id:
          type: integer
        group_id:
          type: integer
        id:
          type: integer
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
    requests.IDRequest:
      type: object
      properties:
        id:
          type: integer
          example: 1
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
