openapi: 3.2.0
info:
  description: '### Configuration API with a tree-like hierarchy.'
  title: CAFA V3 API
  contact:
    email: david.zingerman@erply.com
  version: 4.19.2
tags:
- name: v3
paths:
  /v3/configuration:
    put:
      security:
      - sk: []
      - cc: []
      - hmac-auth: []
      - jwt: []
      description: '`NB`: You cannot have 2 configurations with the same level,level_id, type, name and application

        level, level_id and type are optional fields.'
      tags:
      - v3
      summary: Save or update a configuration
      parameters:
      - description: UNIX timestamp used for the HMAC Auth method only
        name: timestamp
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/configurationRequest'
        description: ConfigurationDbRecord
        required: true
      operationId: putV3Configuration
      x-operation-id-source: derived
  /v3/configuration/{id}:
    get:
      security:
      - sk: []
      - cc: []
      - hmac-auth: []
      - jwt: []
      tags:
      - v3
      summary: Get by ID
      parameters:
      - description: UNIX timestamp used for the HMAC Auth method only
        name: timestamp
        in: header
        schema:
          type: string
      - description: Configuration ID
        name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/configuration'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
      operationId: getV3ConfigurationById
      x-operation-id-source: derived
    put:
      security:
      - sk: []
      - cc: []
      - hmac-auth: []
      - jwt: []
      tags:
      - v3
      summary: Update `value` by ID
      parameters:
      - description: UNIX timestamp used for the HMAC Auth method only
        name: timestamp
        in: header
        schema:
          type: string
      - description: Configuration ID
        name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/valueRequest'
        description: new configuration value
        required: true
      operationId: putV3ConfigurationById
      x-operation-id-source: derived
    delete:
      security:
      - sk: []
      - cc: []
      - hmac-auth: []
      - jwt: []
      tags:
      - v3
      summary: Delete By ID
      parameters:
      - description: UNIX timestamp used for the HMAC Auth method only
        name: timestamp
        in: header
        schema:
          type: string
      - description: configuration ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
      operationId: deleteV3ConfigurationById
      x-operation-id-source: derived
components:
  schemas:
    configurationRequest:
      type: object
      properties:
        application:
          description: Application (s) name that uses CAFA to store configs, application name has to be generated manually before it can be used in Identity Admin.
          type: string
          example: woo-comm
        level:
          description: Level is the operating level where the config will be stored. Has to be one of Company, Warehouse, Pos, User
          type: string
          example: Pos
        level_id:
          description: 'LevelID is a unique value, used to identify the instance of the level.

            for User level, user id

            for Pos - Point of Sale ID. Each Pos belongs to Warehouse. When we query CAFA for configuration on level: ''Pos'', and add ''Look-Deeper: true'' header, if CAFA dooes not find any configuration with the query parameters, CAFA will use the level_id(PointOfSaleID), to find which Warehouse the Pos belongs to and check for configuration with the same name(and type if present)

            Warehouse can use any unique string to identify the instance of its level, because the higher level for each Warehouse is Company level, which can only be one instance per account

            Company level does not need level_id because there can only be one company per account in Erply.'
          type: string
          example: '1'
        name:
          description: Name of the configuration
          type: string
          example: adyen
        type:
          description: 'Type is an optional grouping property, in this case its ''payment'',

            indicating that this configuration belongs to payment integrations group

            used to query groups of related configurations'
          type: string
          example: payment
        value:
          description: 'Value stored by the configuration. Supported types: JSON, JSON array, string'
    response:
      type: object
      properties:
        id:
          type: integer
        message:
          type: string
        statusCode:
          type: string
    configuration:
      type: object
      properties:
        added:
          type: integer
        addedby_id:
          type: integer
        application:
          type: string
          example: erply-to-woo-sync
        changed:
          type: integer
        changedby_id:
          type: integer
        id:
          type: string
        level:
          description: Level is optional
          type: string
          example: Pos
        level_id:
          description: LevelID is optional
          type: string
          example: '1'
        name:
          type: string
          example: adyen
        type:
          description: Type is optional
          type: string
          example: payment
        value: {}
    valueRequest:
      type: object
      properties:
        value:
          description: 'Value stored by the configuration. Supported types: JSON, JSON array, string'
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    hmac-auth:
      type: apiKey
      name: hmac-auth
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
