openapi: 3.2.0
info:
  description: '## Overview


    This application offers an API for managing assignments and tasks.'
  title: assignments Clsf Device Properties API
  contact: {}
  version: 2.36.5
tags:
- name: clsf-device-properties
paths:
  /api/v1/clsf/brand:
    get:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-device-properties
      summary: Look up device brands
      parameters:
      - description: Brand ids
        name: ids
        in: query
        style: form
        explode: false
        schema:
          type: array
          items:
            type: integer
      - description: Language to use when sorting by name (`en`, `et`, `ru` etc.)
        name: lang
        in: query
        schema:
          type: string
      - description: Brand code to search for. Partial matching from the beginning of the code
        name: code
        in: query
        schema:
          type: string
      - description: Result page size
        name: pageSize
        in: query
        schema:
          type: integer
      - description: Result page number
        name: pageNr
        in: query
        schema:
          type: integer
      - description: 'Sorting order. Supported values are: `id`, `name`. Defaults to `id`'
        name: sort
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClsfResponse'
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: getApiV1ClsfBrand
      x-operation-id-source: derived
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-device-properties
      summary: Add a new device brand
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceBrandRequest'
        description: Clsf record
        required: true
      operationId: postApiV1ClsfBrand
      x-operation-id-source: derived
  /api/v1/clsf/brand/{brandId}:
    delete:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-device-properties
      summary: Delete one device brand record
      parameters:
      - description: Record id
        name: brandId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: deleteApiV1ClsfBrandByBrandId
      x-operation-id-source: derived
    patch:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-device-properties
      summary: Update an existing device brand record
      parameters:
      - description: Record id
        name: brandId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceBrandRequest'
        description: Clsf record
        required: true
      operationId: patchApiV1ClsfBrandByBrandId
      x-operation-id-source: derived
  /api/v1/clsf/model:
    get:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-device-properties
      summary: Look up device models
      parameters:
      - description: Device brand code for which models should be returned
        name: brandCode
        in: query
        schema:
          type: string
      - description: Device brand ids
        name: ids
        in: query
        style: form
        explode: false
        schema:
          type: array
          items:
            type: integer
      - description: Language to use when sorting by name (`en`, `et`, `ru` etc.)
        name: lang
        in: query
        schema:
          type: string
      - description: Model code to search for. Partial matching from the beginning of the code
        name: code
        in: query
        schema:
          type: string
      - description: Result page size
        name: pageSize
        in: query
        schema:
          type: integer
      - description: Result page number
        name: pageNr
        in: query
        schema:
          type: integer
      - description: 'Sorting order. Supported values are: `id`, `name`. Defaults to `id`'
        name: sort
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClsfResponse'
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: getApiV1ClsfModel
      x-operation-id-source: derived
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-device-properties
      summary: Add a new device model record
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceModelRequest'
        description: Device model record
        required: true
      operationId: postApiV1ClsfModel
      x-operation-id-source: derived
  /api/v1/clsf/model/{modelId}:
    delete:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-device-properties
      summary: Delete one device model record
      parameters:
      - description: Record id
        name: modelId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: deleteApiV1ClsfModelByModelId
      x-operation-id-source: derived
    patch:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-device-properties
      summary: Update an existing device model record
      parameters:
      - description: Record id
        name: modelId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceModelRequest'
        description: Clsf record
        required: true
      operationId: patchApiV1ClsfModelByModelId
      x-operation-id-source: derived
  /api/v1/clsf/version:
    get:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-device-properties
      summary: Look up device versions
      parameters:
      - description: Device brand code for which versions should be returned
        name: brandCode
        in: query
        schema:
          type: string
      - description: Device model code for which versions should be returned
        name: modelCode
        in: query
        schema:
          type: string
      - description: Device brand ids
        name: ids
        in: query
        style: form
        explode: false
        schema:
          type: array
          items:
            type: integer
      - description: Language to use when sorting by name (`en`, `et`, `ru` etc.)
        name: lang
        in: query
        schema:
          type: string
      - description: Version code to search for. Partial matching from the beginning of the code
        name: code
        in: query
        schema:
          type: string
      - description: Result page size
        name: pageSize
        in: query
        schema:
          type: integer
      - description: Result page number
        name: pageNr
        in: query
        schema:
          type: integer
      - description: 'Sorting order. Supported values are: `id`, `name`. Defaults to `id`'
        name: sort
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClsfResponse'
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: getApiV1ClsfVersion
      x-operation-id-source: derived
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-device-properties
      summary: Add a new device version record
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceVersionRequest'
        description: Device version record
        required: true
      operationId: postApiV1ClsfVersion
      x-operation-id-source: derived
  /api/v1/clsf/version/{versionId}:
    delete:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-device-properties
      summary: Delete one device version record
      parameters:
      - description: Record id
        name: versionId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: deleteApiV1ClsfVersionByVersionId
      x-operation-id-source: derived
    patch:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-device-properties
      summary: Update an existing device version record
      parameters:
      - description: Record id
        name: versionId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceVersionRequest'
        description: Clsf record
        required: true
      operationId: patchApiV1ClsfVersionByVersionId
      x-operation-id-source: derived
components:
  schemas:
    DeviceBrandRequest:
      type: object
      properties:
        code:
          type: string
        id:
          type: integer
        name:
          $ref: '#/components/schemas/core.Translatable'
    ClsfChildResponse:
      type: object
      properties:
        code:
          type: string
        type:
          type: string
    ClsfResponse:
      type: object
      properties:
        children:
          type: array
          items:
            $ref: '#/components/schemas/ClsfChildResponse'
        code:
          type: string
        createdAt:
          type: string
        createdById:
          type: integer
        entity:
          type: string
        id:
          type: integer
        name:
          $ref: '#/components/schemas/core.Translatable'
        parentId:
          type: integer
        updatedAt:
          type: string
        updatedById:
          type: integer
    DeviceModelRequest:
      type: object
      properties:
        brand:
          type: string
        code:
          type: string
        id:
          type: integer
        name:
          $ref: '#/components/schemas/core.Translatable'
    core.Translatable:
      type: object
      properties:
        ar:
          type: string
          example: ' '
        cs:
          type: string
          example: ' '
        da:
          type: string
          example: ' '
        de:
          type: string
          example: ' '
        default:
          type: string
          example: ' '
        el:
          type: string
          example: ' '
        en:
          type: string
          example: ' '
        es:
          type: string
          example: ' '
        et:
          type: string
          example: ' '
        fi:
          type: string
          example: ' '
        fo:
          type: string
          example: ' '
        fr:
          type: string
          example: ' '
        it:
          type: string
          example: ' '
        lt:
          type: string
          example: ' '
        lv:
          type: string
          example: ' '
        nl:
          type: string
          example: ' '
        'no':
          type: string
          example: ' '
        pl:
          type: string
          example: ' '
        ru:
          type: string
          example: ' '
        sv:
          type: string
          example: ' '
        th:
          type: string
          example: ' '
        tr:
          type: string
          example: ' '
        vi:
          type: string
          example: ' '
        zh_Hans:
          type: string
          example: ' '
        zh_Hant:
          type: string
          example: ' '
    DeviceVersionRequest:
      type: object
      properties:
        brand:
          type: string
        code:
          type: string
        id:
          type: integer
        model:
          type: string
        name:
          $ref: '#/components/schemas/core.Translatable'
  securitySchemes:
    AccessToken:
      type: apiKey
      name: accessToken
      in: header
    ErplyClientCode:
      type: apiKey
      name: clientCode
      in: header
    ErplyJWT:
      type: apiKey
      name: jwt
      in: header
    ErplySession:
      type: apiKey
      name: sessionKey
      in: header
    RequestKey:
      type: apiKey
      name: requestKey
      in: header
