openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM Parameter Set To Product Linking API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: Parameter Set To Product Linking
paths:
  /v1/product/parameter/set/{id}/products:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Get products that have values for this st
      tags:
      - Parameter Set To Product Linking
      summary: Get products that have values for this set
      parameters:
      - description: set ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      - description: skip n records
        name: skip
        in: query
        schema:
          type: integer
      - description: 'items to take, default: 20, max: 100000'
        name: take
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/parametermodels.ParameterResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: getV1ProductParameterSetByIdProducts
      x-operation-id-source: derived
components:
  schemas:
    parametermodels.ParameterResponse:
      type: object
      properties:
        added:
          description: Unix timestamp
          type: integer
          example: 1595230999
        addedby_id:
          description: user ID
          type: integer
          example: 1
        changed:
          description: Unix timestamp
          type: integer
          example: 1595230999
        changedby_id:
          description: user ID
          type: integer
          example: 1
        dataset_id:
          type: integer
        id:
          type: integer
        name:
          description: /This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          $ref: '#/components/schemas/Translatable'
        type:
          type: string
        type_id:
          type: integer
        value: {}
        value_id:
          type: integer
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
    Translatable:
      type: object
      properties:
        en:
          description: This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          type: string
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
