openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM Product Extra Field 1 API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: Product Extra Field 1
paths:
  /v1/product/extra/field-1:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Get Product Extra Field
      tags:
      - Product Extra Field 1
      summary: Get Product Extra Field 1
      parameters:
      - description: skip n records
        name: skip
        in: query
        schema:
          type: integer
      - description: 'items to take, default: 20, max: 100000'
        name: take
        in: query
        schema:
          type: integer
      - description: the sort parameter is explained in the `Filtering & Sorting` section on top of the Swagger documentation
        name: sort
        in: query
        schema:
          type: string
      - description: the filter parameter is explained in the `Filtering & Sorting` section on top of the Swagger documentation
        name: filter
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/products.ExtraFieldResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: getV1ProductExtraField1
      x-operation-id-source: derived
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'Extra fields 1 - 4 are just additional classifiers, without any meaning attached.

        Basically, if organizing products by brands, priority groups and families is not sufficient, users can have more such fields, up to 4 additional if they need.'
      tags:
      - Product Extra Field 1
      summary: Create an extra field
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/products.CreateExtraFieldRequest'
        description: Create Extra Field Request
        required: true
      operationId: postV1ProductExtraField1
      x-operation-id-source: derived
  /v1/product/extra/field-1/bulk:
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: each request contains the created resource data
      tags:
      - Product Extra Field 1
      summary: Create Extra Fields in bulk
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.BulkResponseWithResults'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/products.BulkCreateExtraFieldsRequest'
        description: bulk create request
        required: true
      operationId: postV1ProductExtraField1Bulk
      x-operation-id-source: derived
  /v1/product/extra/field-1/bulk/get:
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Product Extra Field 1
      summary: Get Extra Fields in bulk
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/products.BulkReadExtraFieldsResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/parammodels.BulkReadRequest'
        description: requests have the parameters that the original get request has, but in json format. This way you can apply the parameters to each request separately.
        required: true
      operationId: postV1ProductExtraField1BulkGet
      x-operation-id-source: derived
  /v1/product/extra/field-1/{ids}:
    delete:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Product Extra Field 1
      summary: Delete Product Extra Fields
      parameters:
      - description: up to 100 semicolon delimited Product Extra Field IDs
        name: ids
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: deleteV1ProductExtraField1ByIds
      x-operation-id-source: derived
  /v1/product/extra/field-1/{id}:
    patch:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Product Extra Field 1
      summary: Update a Product Extra Field
      parameters:
      - description: Product Extra Field ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/products.UpdateExtraFieldRequest'
        description: request
        required: true
      operationId: patchV1ProductExtraField1ById
      x-operation-id-source: derived
  /v1/product/extra/field-1/{id}/move:
    patch:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'position has to be one of the following: `before` | `after`'
      tags:
      - Product Extra Field 1
      summary: Move Product Extra Field
      parameters:
      - description: Product Extra Field ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.MoveRequest'
        description: moveRequest
        required: true
      operationId: patchV1ProductExtraField1ByIdMove
      x-operation-id-source: derived
components:
  schemas:
    products.ExtraFieldResponse:
      type: object
      properties:
        added:
          description: Unix timestamp
          type: integer
          example: 1595230999
        addedby:
          description: username
          type: string
          example: k@erp.xyz
        changed:
          description: Unix timestamp
          type: integer
          example: 1595230999
        changedby:
          description: username
          type: string
          example: k@erp.xyz
        code:
          description: code of the extra field
          type: string
          example: code
        id:
          description: object ID
          type: integer
          example: 1234
        is_active:
          description: Is the field active?
          type: boolean
          example: true
        name:
          description: /This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          $ref: '#/components/schemas/Translatable'
        order:
          type: integer
          example: 15
    parammodels.SortRequest:
      type: object
      properties:
        desc:
          description: If true - descending, if false - ascending
          type: boolean
        language:
          description: Language in ISO 639-1 standard. Is needed only for translatable properties like description and name.
          type: string
          example: en
        selector:
          description: 'JSON field. For description: description_plain or description_html'
          type: string
          example: name
    parammodels.BulkReadRequest:
      type: object
      properties:
        requests:
          type: array
          items:
            $ref: '#/components/schemas/parammodels.ReadRequestWithTotalCount'
    products.UpdateExtraFieldRequest:
      type: object
      properties:
        code:
          description: code of the extra field
          type: string
          example: code
        is_active:
          description: Is the field active?
          type: boolean
          example: true
        name:
          description: /This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          $ref: '#/components/schemas/Translatable'
    products.BulkReadExtraFieldsResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/products.BulkReadExtraFieldsResponseItem'
    responses.BulkResult:
      type: object
      properties:
        message:
          type: string
          example: some message
        resourceId:
          description: identifier of the REST-ful response
          type: integer
          example: 2
        resultId:
          description: identifier of the result item
          type: integer
          example: 2
    models.MoveRequest:
      type: object
      properties:
        position:
          description: Position has to be  lastChild | before | after
          type: string
          example: after
        target_id:
          description: Target ID represents the object that the requested object is put after, or before, or becomes the last child of
          type: integer
    responses.Response:
      type: object
      properties:
        id:
          type: integer
          example: 73
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
    products.BulkCreateExtraFieldsRequest:
      type: object
      properties:
        requests:
          type: array
          items:
            $ref: '#/components/schemas/products.CreateExtraFieldRequest'
    parammodels.FilterJSON:
      type: object
      properties:
        fieldName:
          type: string
          example: group_id
        operandBefore:
          description: supported values are "and", "or"
          type: string
          example: or
        operator:
          type: string
          example: '='
        sliceValue:
          description: to be used if the value is a slice
          type: array
          items: {}
        value:
          type: object
    parammodels.PaginationParameters:
      type: object
      properties:
        skip:
          type: integer
        take:
          type: integer
    products.CreateExtraFieldRequest:
      type: object
      properties:
        code:
          description: code of the extra field
          type: string
          example: code
        is_active:
          description: Is the field active?
          type: boolean
          example: true
        name:
          description: /This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          $ref: '#/components/schemas/Translatable'
    products.BulkReadExtraFieldsResponseItem:
      type: object
      properties:
        extraFields:
          type: array
          items:
            $ref: '#/components/schemas/products.ExtraFieldResponse'
        message:
          type: string
          example: some message
        resultId:
          description: id of the response, if requested 3 read requests each ID represents 1 response item
          type: integer
        totalCount:
          description: total number of records (ignores skip & take parameters)
          type: integer
    Translatable:
      type: object
      properties:
        en:
          description: This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          type: string
    parammodels.ReadRequestWithTotalCount:
      type: object
      properties:
        filters:
          type: array
          items:
            $ref: '#/components/schemas/parammodels.FilterJSON'
        paginationParameters:
          $ref: '#/components/schemas/parammodels.PaginationParameters'
        sortingParameters:
          $ref: '#/components/schemas/parammodels.SortRequest'
        withTotalCount:
          type: boolean
    responses.BulkResponseWithResults:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/responses.BulkResult'
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
