openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM Warehouse Locations API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: Warehouse Locations
paths:
  /v1/warehouse/locations:
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Warehouse Locations
      summary: Create a Warehouse Location
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/warehouses.CreateLocationRequest'
        description: request
        required: true
      operationId: postV1WarehouseLocations
      x-operation-id-source: derived
  /v1/warehouse/locations/{ids}:
    delete:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Warehouse Locations
      summary: Delete Warehouse Locations by IDs
      parameters:
      - description: up to 100 semicolon delimited Warehouse Location IDs
        name: ids
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: deleteV1WarehouseLocationsByIds
      x-operation-id-source: derived
  /v1/warehouse/locations/{id}:
    patch:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Warehouse Locations
      summary: Update a warehouse location
      parameters:
      - description: location ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/warehouses.UpdateLocationRequest'
        description: update request
        required: true
      operationId: patchV1WarehouseLocationsById
      x-operation-id-source: derived
components:
  schemas:
    warehouses.CreateLocationRequest:
      type: object
      properties:
        name:
          type: string
          example: loc1
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
    responses.Response:
      type: object
      properties:
        id:
          type: integer
          example: 73
    warehouses.UpdateLocationRequest:
      type: object
      properties:
        name:
          type: string
          example: loc1
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
