openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM Product Replacement API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: Product Replacement
paths:
  /v1/product/replacements/{ids}:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'Not to be mistaken with the product substituting feature. This feature is meant for complete replacement

        of old products (discontinued etc).

        A product cannot replace multiple products. Api can still return multiple replacements however since

        api also returns inherited replacements from the replaced products.'
      tags:
      - Product Replacement
      summary: Get products replacement information
      parameters:
      - description: product IDs
        name: ids
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: getV1ProductReplacementsByIds
      x-operation-id-source: derived
  /v1/product/{newProductId}/replace/{oldProductId}:
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'Not to be mistaken with the product substituting feature. This feature is meant for complete replacement

        of old products (discontinued etc).

        If the replaced product has replacements on its own then the new product will also inherit all of them.'
      tags:
      - Product Replacement
      summary: Create a new product replacement
      parameters:
      - description: product ID - product that replaces the other product
        name: newProductId
        in: path
        required: true
        schema:
          type: string
      - description: product ID - product that will be replaced
        name: oldProductId
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: postV1ProductByNewProductIdReplaceByOldProductId
      x-operation-id-source: derived
    delete:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'Not to be mistaken with the product substituting feature. This feature is meant for complete replacement

        of old products (discontinued etc).

        Call only removes the requested replacement, it will not remove replacements that might have been inherited when the replacement was added.'
      tags:
      - Product Replacement
      summary: Delete an existing product replacement
      parameters:
      - description: product ID - product that replaces the other product
        name: newProductId
        in: path
        required: true
        schema:
          type: string
      - description: product ID - product that will be replaced
        name: oldProductId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: deleteV1ProductByNewProductIdReplaceByOldProductId
      x-operation-id-source: derived
components:
  schemas:
    responses.Response:
      type: object
      properties:
        id:
          type: integer
          example: 73
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
