openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM Product Parameter Validation Rule API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: Product Parameter Validation Rule
paths:
  /v1/product/parameter/validation/rule:
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'The validation rule types are: REQUIRED, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, INPUT_CASE, PRECISION

        Rule "value" or whatever to call this: the numeric qualifier that goes hand in hand with that particular rule type. Eg. I specify that my parameter must have at least a minimum number of characters and that minimum number is 5.

        For type REQUIRED, leave empty.

        For type MIN_LENGTH, input the required minimum length as an integer.

        For type MAX_LENGTH, input the required maximum length as an integer.

        For type MIN_VALUE, input the minimum allowed value as a signed integer or decimal (eg. “0”, “-1”, “25.6”, “-9.999999” etc.)

        For type MAX_VALUE, input the maximum allowed value as a signed integer or decimal.

        For type INPUT_CASE, input 0 for "LOWERCASE" or 1 for “UPPERCASE”.

        For type PRECISION, input the number of allowed decimal places as an integer (eg. “0”, “1”, or “2”)'
      tags:
      - Product Parameter Validation Rule
      summary: Create Product Parameter Validation Rule
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/parametermodels.ValidationRuleRequest'
        description: Parameter Validation Rule
        required: true
      operationId: postV1ProductParameterValidationRule
      x-operation-id-source: derived
  /v1/product/parameter/validation/rule/{ids}:
    delete:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Product Parameter Validation Rule
      summary: Delete Product Parameter Validation Rules by IDs
      parameters:
      - description: up to 100 semicolon delimited validation rule IDs
        name: ids
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: deleteV1ProductParameterValidationRuleByIds
      x-operation-id-source: derived
  /v1/product/parameter/validation/rule/{id}:
    put:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Product Parameter Validation Rule
      summary: Update Product Parameter Validation Rule
      parameters:
      - description: ValidationRule ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/parametermodels.ValidationRuleUpdateRequest'
        description: Validation Rule value
        required: true
      operationId: putV1ProductParameterValidationRuleById
      x-operation-id-source: derived
  /v1/product/parameter/{id}/validation/rule:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Get Product Parameter Validation Rule
      tags:
      - Product Parameter Validation Rule
      summary: Get Product Parameter Validation Rules
      parameters:
      - description: parameter ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      - description: skip n records
        name: skip
        in: query
        schema:
          type: integer
      - description: amount to take
        name: take
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/parametermodels.ValidationRuleResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: getV1ProductParameterByIdValidationRule
      x-operation-id-source: derived
components:
  schemas:
    parametermodels.ValidationRuleResponse:
      type: object
      properties:
        added:
          description: Unix timestamp
          type: integer
          example: 1595230999
        addedby_id:
          description: user ID
          type: integer
          example: 1
        changed:
          description: Unix timestamp
          type: integer
          example: 1595230999
        changedby_id:
          description: user ID
          type: integer
          example: 1
        id:
          type: integer
        parameter_id:
          type: integer
        rule: {}
        type:
          type: string
    parametermodels.ValidationRuleUpdateRequest:
      type: object
      properties:
        rule:
          description: 'Rule "value" or whatever to call this: the numeric qualifier that goes hand in hand with that particular rule type. Eg. I specify that my parameter must have at least a minimum number of characters and that minimum number is 5.

            For type REQUIRED, leave empty.

            For type MIN_LENGTH, input the required minimum length as an integer.

            For type MAX_LENGTH, input the required maximum length as an integer.

            For type MIN_VALUE, input the minimum allowed value as a signed integer or decimal (eg. “0”, “-1”, “25.6”, “-9.999999” etc.)

            For type MAX_VALUE, input the maximum allowed value as a signed integer or decimal.

            For type INPUT_CASE, input 0 for "LOWERCASE" or 1 for “UPPERCASE”.

            For type PRECISION, input the number of allowed decimal places as an integer (eg. “0”, “1”, or “2”)'
          type: number
          example: 25.6
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
    parametermodels.ValidationRuleRequest:
      type: object
      properties:
        parameter_id:
          type: integer
          example: 1
        rule:
          description: 'Rule "value" or whatever to call this: the numeric qualifier that goes hand in hand with that particular rule type. Eg. I specify that my parameter must have at least a minimum number of characters and that minimum number is 5.

            For type REQUIRED, leave empty.

            For type MIN_LENGTH, input the required minimum length as an integer.

            For type MAX_LENGTH, input the required maximum length as an integer.

            For type MIN_VALUE, input the minimum allowed value as a signed integer or decimal (eg. “0”, “-1”, “25.6”, “-9.999999” etc.)

            For type MAX_VALUE, input the maximum allowed value as a signed integer or decimal.

            For type INPUT_CASE, input 0 for "LOWERCASE" or 1 for “UPPERCASE”.

            For type PRECISION, input the number of allowed decimal places as an integer (eg. “0”, “1”, or “2”)'
          type: number
          example: 25
        type:
          description: Type of the validation rule. Can be REQUIRED, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, INPUT_CASE and PRECISION
          type: string
          example: MIN_LENGTH
    responses.Response:
      type: object
      properties:
        id:
          type: integer
          example: 73
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
