openapi: 3.2.0
info:
  description: '## Overview


    This application offers an API for managing assignments and tasks.'
  title: assignments Clsf API
  contact: {}
  version: 2.36.5
tags:
- name: clsf
paths:
  /api/v1/clsf/priority:
    get:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf
      summary: Look up priorities
      parameters:
      - description: Priority ids
        name: ids
        in: query
        style: form
        explode: false
        schema:
          type: array
          items:
            type: integer
      - description: Entity for which priority should be returned (`raji`)
        name: entity
        in: query
        required: true
        schema:
          type: string
      - description: Language to use when sorting by name (`en`, `et`, `ru` etc.)
        name: lang
        in: query
        schema:
          type: string
      - description: Priority code to search for. Partial matching from the beginning of the code
        name: code
        in: query
        schema:
          type: string
      - description: Result page size
        name: pageSize
        in: query
        schema:
          type: integer
      - description: Result page number
        name: pageNr
        in: query
        schema:
          type: integer
      - description: 'Sorting order. Supported values are: `id`, `name`. Defaults to `id`'
        name: sort
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClsfResponse'
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: getApiV1ClsfPriority
      x-operation-id-source: derived
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf
      summary: Add a new priority
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PriorityRequest'
        description: Clsf record
        required: true
      operationId: postApiV1ClsfPriority
      x-operation-id-source: derived
  /api/v1/clsf/priority/{priorityId}:
    delete:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf
      summary: Delete one priority record
      parameters:
      - description: Record id
        name: priorityId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: deleteApiV1ClsfPriorityByPriorityId
      x-operation-id-source: derived
    patch:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf
      summary: Update an existing priority record
      parameters:
      - description: Record id
        name: priorityId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PriorityRequest'
        description: Clsf record
        required: true
      operationId: patchApiV1ClsfPriorityByPriorityId
      x-operation-id-source: derived
  /api/v1/clsf/state:
    get:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf
      summary: Look up states
      parameters:
      - description: Object type for which states should be returned. One of [workorder row_work row_product transaction task_schedule product_stock raji]
        name: entity
        in: query
        required: true
        schema:
          type: string
      - description: Type code for which states should be returned
        name: typeCode
        in: query
        schema:
          type: string
      - description: State ids
        name: ids
        in: query
        style: form
        explode: false
        schema:
          type: array
          items:
            type: integer
      - description: Language to use when sorting by name
        name: lang
        in: query
        schema:
          type: string
      - description: State code to search for. Partial matching from the beginning of the code
        name: code
        in: query
        schema:
          type: string
      - description: Result page size
        name: pageSize
        in: query
        schema:
          type: integer
      - description: Result page number
        name: pageNr
        in: query
        schema:
          type: integer
      - description: 'Sorting order. Supported values are: `id`, `name`. Defaults to `id`'
        name: sort
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClsfResponse'
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: getApiV1ClsfState
      x-operation-id-source: derived
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf
      summary: Add a new state record
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StateRequest'
        description: State record
        required: true
      operationId: postApiV1ClsfState
      x-operation-id-source: derived
  /api/v1/clsf/state/{stateId}:
    delete:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf
      summary: Delete one state record
      parameters:
      - description: Record id
        name: stateId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: deleteApiV1ClsfStateByStateId
      x-operation-id-source: derived
    patch:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf
      summary: Update an existing state record
      parameters:
      - description: Record id
        name: stateId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StateRequest'
        description: State record
        required: true
      operationId: patchApiV1ClsfStateByStateId
      x-operation-id-source: derived
  /api/v1/clsf/unit:
    get:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf
      summary: Look up product units
      parameters:
      - description: Device brand ids
        name: ids
        in: query
        style: form
        explode: false
        schema:
          type: array
          items:
            type: integer
      - description: Result page size
        name: pageSize
        in: query
        schema:
          type: integer
      - description: Result page number
        name: pageNr
        in: query
        schema:
          type: integer
      - description: Sorting order
        name: sort
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClsfResponse'
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: getApiV1ClsfUnit
      x-operation-id-source: derived
  /api/v1/clsf/workorder-type:
    get:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf
      summary: Look up workorder types
      parameters:
      - description: Workorder type ids
        name: ids
        in: query
        style: form
        explode: false
        schema:
          type: array
          items:
            type: integer
      - description: Entity for which workorder types should be returned (`workorder`, `raji`). Defaults to `workorder`
        name: entity
        in: query
        schema:
          type: string
      - description: Language to use when sorting by name (`en`, `et`, `ru` etc.)
        name: lang
        in: query
        schema:
          type: string
      - description: Type code to search for. Partial matching from the beginning of the code
        name: code
        in: query
        schema:
          type: string
      - description: Result page size
        name: pageSize
        in: query
        schema:
          type: integer
      - description: Result page number
        name: pageNr
        in: query
        schema:
          type: integer
      - description: 'Sorting order. Supported values are: `id`, `name`. Defaults to `id`'
        name: sort
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClsfResponse'
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: getApiV1ClsfWorkorderType
      x-operation-id-source: derived
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf
      summary: Add a new workorder type
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkorderTypeRequest'
        description: Clsf record
        required: true
      operationId: postApiV1ClsfWorkorderType
      x-operation-id-source: derived
  /api/v1/clsf/workorder-type/{typeId}:
    delete:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf
      summary: Delete one workorder type record
      parameters:
      - description: Record id
        name: typeId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: deleteApiV1ClsfWorkorderTypeByTypeId
      x-operation-id-source: derived
    patch:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf
      summary: Update an existing workorder type record
      parameters:
      - description: Record id
        name: typeId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkorderTypeRequest'
        description: Clsf record
        required: true
      operationId: patchApiV1ClsfWorkorderTypeByTypeId
      x-operation-id-source: derived
components:
  schemas:
    WorkorderTypeRequest:
      type: object
      properties:
        code:
          type: string
        entity:
          type: string
        id:
          type: integer
        name:
          $ref: '#/components/schemas/core.Translatable'
    PriorityRequest:
      type: object
      properties:
        code:
          type: string
        entity:
          type: string
        id:
          type: integer
        name:
          $ref: '#/components/schemas/core.Translatable'
    ClsfChildResponse:
      type: object
      properties:
        code:
          type: string
        type:
          type: string
    StateRequest:
      type: object
      properties:
        code:
          type: string
        entity:
          type: string
        id:
          type: integer
        name:
          $ref: '#/components/schemas/core.Translatable'
        type:
          type: string
    core.Translatable:
      type: object
      properties:
        ar:
          type: string
          example: ' '
        cs:
          type: string
          example: ' '
        da:
          type: string
          example: ' '
        de:
          type: string
          example: ' '
        default:
          type: string
          example: ' '
        el:
          type: string
          example: ' '
        en:
          type: string
          example: ' '
        es:
          type: string
          example: ' '
        et:
          type: string
          example: ' '
        fi:
          type: string
          example: ' '
        fo:
          type: string
          example: ' '
        fr:
          type: string
          example: ' '
        it:
          type: string
          example: ' '
        lt:
          type: string
          example: ' '
        lv:
          type: string
          example: ' '
        nl:
          type: string
          example: ' '
        'no':
          type: string
          example: ' '
        pl:
          type: string
          example: ' '
        ru:
          type: string
          example: ' '
        sv:
          type: string
          example: ' '
        th:
          type: string
          example: ' '
        tr:
          type: string
          example: ' '
        vi:
          type: string
          example: ' '
        zh_Hans:
          type: string
          example: ' '
        zh_Hant:
          type: string
          example: ' '
    ClsfResponse:
      type: object
      properties:
        children:
          type: array
          items:
            $ref: '#/components/schemas/ClsfChildResponse'
        code:
          type: string
        createdAt:
          type: string
        createdById:
          type: integer
        entity:
          type: string
        id:
          type: integer
        name:
          $ref: '#/components/schemas/core.Translatable'
        parentId:
          type: integer
        updatedAt:
          type: string
        updatedById:
          type: integer
  securitySchemes:
    AccessToken:
      type: apiKey
      name: accessToken
      in: header
    ErplyClientCode:
      type: apiKey
      name: clientCode
      in: header
    ErplyJWT:
      type: apiKey
      name: jwt
      in: header
    ErplySession:
      type: apiKey
      name: sessionKey
      in: header
    RequestKey:
      type: apiKey
      name: requestKey
      in: header
