openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM Tasks API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: Tasks
paths:
  /v1/tasks/recurring-billing-update-tax-rate:
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Tasks
      summary: Update tax rate for recurring bills
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.TaxRateUpdateInputOnRecurringBillings'
        description: inputs
        required: true
      operationId: postV1TasksRecurringBillingUpdateTaxRate
      x-operation-id-source: derived
  /v1/tasks/update-tax-rate:
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Tasks
      summary: Update tax rate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.TaxRateUpdateInput'
        description: inputs
        required: true
      operationId: postV1TasksUpdateTaxRate
      x-operation-id-source: derived
components:
  schemas:
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
    models.TaxRateUpdateInput:
      type: object
      properties:
        newRate:
          type: number
        oldRate:
          type: number
        preservePricesWithTax:
          type: boolean
        pricelistIds:
          type: array
          items:
            type: integer
    models.TaxRateUpdateInputOnRecurringBillings:
      type: object
      properties:
        newRate:
          type: number
        oldRate:
          type: number
        preservePricesWithTax:
          type: boolean
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
