openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM Assortment API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: Assortment
paths:
  /v1/assortment:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Assortment
      summary: Get Assortments
      parameters:
      - description: skip n records
        name: skip
        in: query
        schema:
          type: integer
      - description: 'items to take, default: 20, max: 100000'
        name: take
        in: query
        schema:
          type: integer
      - description: the filter parameter is explained in the `Filtering & Sorting` section on top of the Swagger documentation
        name: filter
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/models.AssortmentResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: getV1Assortment
      x-operation-id-source: derived
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Assortment
      summary: Create Assortment
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.AssortmentRequest'
        description: Name and code
        required: true
      operationId: postV1Assortment
      x-operation-id-source: derived
  /v1/assortment/{ids}:
    delete:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Delete Assortments will also delete the links to products and the linked products if they are not used in any other assortment.
      tags:
      - Assortment
      summary: Delete Assortments & the related links to products and products
      parameters:
      - description: up to 100 semicolon delimited assortment ids
        name: ids
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: deleteV1AssortmentByIds
      x-operation-id-source: derived
  /v1/assortment/{id}:
    put:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Assortment
      summary: Update Assortment
      parameters:
      - description: Assortment ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.AssortmentRequest'
        description: AssortmentRequest
        required: true
      operationId: putV1AssortmentById
      x-operation-id-source: derived
components:
  schemas:
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
    responses.Response:
      type: object
      properties:
        id:
          type: integer
          example: 73
    models.AssortmentResponse:
      type: object
      properties:
        added:
          description: Unix timestamp
          type: integer
          example: 1595230999
        addedby:
          description: username
          type: string
          example: k@erp.xyz
        changed:
          description: Unix timestamp
          type: integer
          example: 1595230999
        changedby:
          description: username
          type: string
          example: k@erp.xyz
        code:
          type: string
        id:
          type: integer
        name:
          description: /This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          $ref: '#/components/schemas/Translatable'
    models.AssortmentRequest:
      type: object
      properties:
        code:
          description: Code
          type: string
        name:
          description: /This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          $ref: '#/components/schemas/Translatable'
    Translatable:
      type: object
      properties:
        en:
          description: This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          type: string
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
