openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM Product Priority Groups API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: Product Priority Groups
paths:
  /v1/product/priority/group:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Priority groups are a product classifier. Priority groups are a flat list (no hierarchy) and have multilingual names. A product can be associated with only one priority group.
      tags:
      - Product Priority Groups
      summary: Read Priority Groups
      parameters:
      - description: skip n records
        name: skip
        in: query
        schema:
          type: integer
      - description: 'items to take, default: 20, max: 100000'
        name: take
        in: query
        schema:
          type: integer
      - description: the sort parameter is explained in the `Filtering & Sorting` section on top of the Swagger documentation
        name: sort
        in: query
        schema:
          type: string
      - description: the filter parameter is explained in the `Filtering & Sorting` section on top of the Swagger documentation
        name: filter
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/groupmodels.PriorityGroupResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: getV1ProductPriorityGroup
      x-operation-id-source: derived
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Product Priority Groups
      summary: Create a Priority Group
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/groupmodels.PriorityGroupCreateRequest'
        description: request
        required: true
      operationId: postV1ProductPriorityGroup
      x-operation-id-source: derived
  /v1/product/priority/group/bulk:
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: each request contains the created resource data
      tags:
      - Product Priority Groups
      summary: Create priority groups in bulk
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.BulkResponseWithResults'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/groupmodels.BulkCreatePriorityGroupRequest'
        description: bulk create request
        required: true
      operationId: postV1ProductPriorityGroupBulk
      x-operation-id-source: derived
  /v1/product/priority/group/bulk/get:
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Product Priority Groups
      summary: Get priority groups in bulk
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/groupmodels.BulkReadPriorityGroupsResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/parammodels.BulkReadRequest'
        description: requests have the parameters that the original get request has, but in json format. This way you can apply the parameters to each request separately.
        required: true
      operationId: postV1ProductPriorityGroupBulkGet
      x-operation-id-source: derived
  /v1/product/priority/group/{ids}:
    delete:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Product Priority Groups
      summary: Delete Priority Groups
      parameters:
      - description: ' up to 100 semicolon delimited priority group IDs'
        name: ids
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: deleteV1ProductPriorityGroupByIds
      x-operation-id-source: derived
  /v1/product/priority/group/{id}:
    put:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Product Priority Groups
      summary: Update a Priority Group
      parameters:
      - description: priority group ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/groupmodels.PriorityGroupCreateRequest'
        description: request
        required: true
      operationId: putV1ProductPriorityGroupById
      x-operation-id-source: derived
  /v1/product/priority/group/{id}/move:
    put:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'position has to be one of the following: `before` | `after`'
      tags:
      - Product Priority Groups
      summary: Move Priority Group
      parameters:
      - description: priority group ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.MoveRequest'
        description: moveRequest
        required: true
      operationId: putV1ProductPriorityGroupByIdMove
      x-operation-id-source: derived
components:
  schemas:
    groupmodels.BulkReadPriorityGroupsResponseItem:
      type: object
      properties:
        message:
          type: string
          example: some message
        priority_groups:
          type: array
          items:
            $ref: '#/components/schemas/groupmodels.PriorityGroupResponse'
        resultId:
          description: id of the response, if requested 3 read requests each ID represents 1 response item
          type: integer
        totalCount:
          description: total number of records (ignores skip & take parameters)
          type: integer
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
    responses.BulkResponseWithResults:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/responses.BulkResult'
    parammodels.ReadRequestWithTotalCount:
      type: object
      properties:
        filters:
          type: array
          items:
            $ref: '#/components/schemas/parammodels.FilterJSON'
        paginationParameters:
          $ref: '#/components/schemas/parammodels.PaginationParameters'
        sortingParameters:
          $ref: '#/components/schemas/parammodels.SortRequest'
        withTotalCount:
          type: boolean
    parammodels.SortRequest:
      type: object
      properties:
        desc:
          description: If true - descending, if false - ascending
          type: boolean
        language:
          description: Language in ISO 639-1 standard. Is needed only for translatable properties like description and name.
          type: string
          example: en
        selector:
          description: 'JSON field. For description: description_plain or description_html'
          type: string
          example: name
    groupmodels.BulkCreatePriorityGroupRequest:
      type: object
      properties:
        requests:
          type: array
          items:
            $ref: '#/components/schemas/groupmodels.PriorityGroupCreateRequest'
    parammodels.BulkReadRequest:
      type: object
      properties:
        requests:
          type: array
          items:
            $ref: '#/components/schemas/parammodels.ReadRequestWithTotalCount'
    groupmodels.PriorityGroupCreateRequest:
      type: object
      properties:
        name:
          description: /This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          $ref: '#/components/schemas/Translatable'
    parammodels.PaginationParameters:
      type: object
      properties:
        skip:
          type: integer
        take:
          type: integer
    models.MoveRequest:
      type: object
      properties:
        position:
          description: Position has to be  lastChild | before | after
          type: string
          example: after
        target_id:
          description: Target ID represents the object that the requested object is put after, or before, or becomes the last child of
          type: integer
    groupmodels.PriorityGroupResponse:
      type: object
      properties:
        added:
          description: Unix timestamp
          type: integer
          example: 1595230999
        addedby:
          description: username
          type: string
          example: k@erp.xyz
        changed:
          description: Unix timestamp
          type: integer
          example: 1595230999
        changedby:
          description: username
          type: string
          example: k@erp.xyz
        id:
          description: object ID
          type: integer
          example: 1234
        name:
          description: /This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          $ref: '#/components/schemas/Translatable'
        order:
          type: integer
          example: 15
    groupmodels.BulkReadPriorityGroupsResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/groupmodels.BulkReadPriorityGroupsResponseItem'
    responses.Response:
      type: object
      properties:
        id:
          type: integer
          example: 73
    responses.BulkResult:
      type: object
      properties:
        message:
          type: string
          example: some message
        resourceId:
          description: identifier of the REST-ful response
          type: integer
          example: 2
        resultId:
          description: identifier of the result item
          type: integer
          example: 2
    Translatable:
      type: object
      properties:
        en:
          description: This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          type: string
    parammodels.FilterJSON:
      type: object
      properties:
        fieldName:
          type: string
          example: group_id
        operandBefore:
          description: supported values are "and", "or"
          type: string
          example: or
        operator:
          type: string
          example: '='
        sliceValue:
          description: to be used if the value is a slice
          type: array
          items: {}
        value:
          type: object
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
