swagger: '2.0'
info:
  description: "\n\n## Overview\n\n\n\nThis application offers an API for managing assignments and tasks.\n\n\n\nGraphQL endpoint for the same API is [also available](/graph)\n\n\n\n<details><summary>Authentication</summary>\n\n\n\n> \n\n> Authenticate using your Erply credentials and get a sessionKey. This sessionKey and your Erply clientCode must be provided in the HTTP headers of every request. You do not have to authenticate against this API - valid Erply sessionKey-s from other sources are also acceptable. To authenticate using this API, use the `POST /api/v1/auth` endpoint.\n\n>\n\n</details>\n\n"
  title: assignments Assortment Parameter Set to Group Linking API
  contact: {}
  version: 2.36.5
host: ''
basePath: ''
schemes: []
tags:
- name: Parameter Set to Group Linking
paths:
  /v1/product/parameter/set/groups/{ids}:
    delete:
      security:
      - sk: []
      - cc: []
      - jwt: []
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - Parameter Set to Group Linking
      summary: Delete Linked Groups
      parameters:
      - type: string
        description: up to 100 semicolon delimited link IDs
        name: ids
        in: path
        required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/responses.Response'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
  /v1/product/parameter/set/{id}/groups:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Get Linked Groups
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - Parameter Set to Group Linking
      summary: Get Linked Groups
      parameters:
      - type: integer
        description: set ID
        name: id
        in: path
        required: true
      - type: integer
        description: skip n records
        name: skip
        in: query
      - type: integer
        description: amount to take
        name: take
        in: query
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/models.SetToGroupResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Link Group
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - Parameter Set to Group Linking
      summary: Link Group
      parameters:
      - type: integer
        description: set ID
        name: id
        in: path
        required: true
      - description: group ID
        name: id
        in: body
        required: true
        schema:
          $ref: '#/definitions/requests.IDRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        '201':
          description: Created
          schema:
            $ref: '#/definitions/responses.Response'
        '304':
          description: Not Modified
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
definitions:
  responses.Response:
    type: object
    properties:
      id:
        type: integer
        example: 73
  requests.IDRequest:
    type: object
    properties:
      id:
        type: integer
        example: 1
  responses.MessageResponse:
    type: object
    properties:
      message:
        type: string
        example: some message
  models.SetToGroupResponse:
    type: object
    properties:
      added:
        description: Unix timestamp
        type: integer
        example: 1595230999
      addedby_id:
        description: user ID
        type: integer
        example: 1
      changed:
        description: Unix timestamp
        type: integer
        example: 1595230999
      changedby_id:
        description: user ID
        type: integer
        example: 1
      dataset_id:
        type: integer
      group_id:
        type: integer
      id:
        type: integer
securityDefinitions:
  AccessToken:
    type: apiKey
    name: accessToken
    in: header
  ErplyClientCode:
    type: apiKey
    name: clientCode
    in: header
  ErplyJWT:
    type: apiKey
    name: jwt
    in: header
  ErplySession:
    type: apiKey
    name: sessionKey
    in: header
  RequestKey:
    type: apiKey
    name: requestKey
    in: header
