swagger: '2.0'
info:
  description: "\n\n## Overview\n\n\n\nThis application offers an API for managing assignments and tasks.\n\n\n\nGraphQL endpoint for the same API is [also available](/graph)\n\n\n\n<details><summary>Authentication</summary>\n\n\n\n> \n\n> Authenticate using your Erply credentials and get a sessionKey. This sessionKey and your Erply clientCode must be provided in the HTTP headers of every request. You do not have to authenticate against this API - valid Erply sessionKey-s from other sources are also acceptable. To authenticate using this API, use the `POST /api/v1/auth` endpoint.\n\n>\n\n</details>\n\n"
  title: assignments Assortment Product Parameter Validation Rule API
  contact: {}
  version: 2.36.5
host: ''
basePath: ''
schemes: []
tags:
- name: Product Parameter Validation Rule
paths:
  /v1/product/parameter/validation/rule:
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'The validation rule types are: REQUIRED,  MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, INPUT_CASE, PRECISION

        Rule "value" or whatever to call this: the numeric qualifier that goes hand in hand with that particular rule type. Eg. I specify that my parameter must have at least a minimum number of characters and that minimum number is 5.

        For type REQUIRED, leave empty.

        For type MIN_LENGTH, input the required minimum length as an integer.

        For type MAX_LENGTH, input the required maximum length as an integer.

        For type MIN_VALUE, input the minimum allowed value as a signed integer or decimal (eg. “0”, “-1”, “25.6”, “-9.999999” etc.)

        For type MAX_VALUE, input the maximum allowed value as a signed integer or decimal.

        For type INPUT_CASE, input 0 for "LOWERCASE" or 1 for “UPPERCASE”.

        For type PRECISION, input the number of allowed decimal places as an integer (eg. “0”, “1”, or “2”)'
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - Product Parameter Validation Rule
      summary: Create Product Parameter Validation Rule
      parameters:
      - description: Parameter Validation Rule
        name: rule
        in: body
        required: true
        schema:
          $ref: '#/definitions/parametermodels.ValidationRuleRequest'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/responses.Response'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
  /v1/product/parameter/validation/rule/{ids}:
    delete:
      security:
      - sk: []
      - cc: []
      - jwt: []
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - Product Parameter Validation Rule
      summary: Delete Product Parameter Validation Rules by IDs
      parameters:
      - type: string
        description: up to 100 semicolon delimited validation rule IDs
        name: ids
        in: path
        required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/responses.Response'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
  /v1/product/parameter/validation/rule/{id}:
    put:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Update Product Parameter Validation Rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - Product Parameter Validation Rule
      summary: Update Product Parameter Validation Rule
      parameters:
      - description: Validation Rule value
        name: rule
        in: body
        required: true
        schema:
          $ref: '#/definitions/parametermodels.ValidationRuleUpdateRequest'
      - type: integer
        description: ValidationRule ID
        name: id
        in: path
        required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/responses.Response'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
  /v1/product/parameter/{id}/validation/rule:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Get Product Parameter Validation Rule
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - Product Parameter Validation Rule
      summary: Get Product Parameter Validation Rules
      parameters:
      - type: integer
        description: parameter ID
        name: id
        in: path
        required: true
      - type: integer
        description: skip n records
        name: skip
        in: query
      - type: integer
        description: amount to take
        name: take
        in: query
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/parametermodels.ValidationRuleResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
definitions:
  responses.Response:
    type: object
    properties:
      id:
        type: integer
        example: 73
  parametermodels.ValidationRuleRequest:
    type: object
    properties:
      parameter_id:
        type: integer
        example: 1
      rule:
        description: 'Rule "value" or whatever to call this: the numeric qualifier that goes hand in hand with that particular rule type. Eg. I specify that my parameter must have at least a minimum number of characters and that minimum number is 5.

          For type REQUIRED, leave empty.

          For type MIN_LENGTH, input the required minimum length as an integer.

          For type MAX_LENGTH, input the required maximum length as an integer.

          For type MIN_VALUE, input the minimum allowed value as a signed integer or decimal (eg. “0”, “-1”, “25.6”, “-9.999999” etc.)

          For type MAX_VALUE, input the maximum allowed value as a signed integer or decimal.

          For type INPUT_CASE, input 0 for "LOWERCASE" or 1 for “UPPERCASE”.

          For type PRECISION, input the number of allowed decimal places as an integer (eg. “0”, “1”, or “2”)'
        type: number
        example: 25
      type:
        description: Type of the validation rule. Can be REQUIRED, MIN_LENGTH, MAX_LENGTH, MIN_VALUE, MAX_VALUE, INPUT_CASE and PRECISION
        type: string
        example: MIN_LENGTH
  responses.MessageResponse:
    type: object
    properties:
      message:
        type: string
        example: some message
  parametermodels.ValidationRuleResponse:
    type: object
    properties:
      added:
        description: Unix timestamp
        type: integer
        example: 1595230999
      addedby_id:
        description: user ID
        type: integer
        example: 1
      changed:
        description: Unix timestamp
        type: integer
        example: 1595230999
      changedby_id:
        description: user ID
        type: integer
        example: 1
      id:
        type: integer
      parameter_id:
        type: integer
      rule: {}
      type:
        type: string
  parametermodels.ValidationRuleUpdateRequest:
    type: object
    properties:
      rule:
        description: 'Rule "value" or whatever to call this: the numeric qualifier that goes hand in hand with that particular rule type. Eg. I specify that my parameter must have at least a minimum number of characters and that minimum number is 5.

          For type REQUIRED, leave empty.

          For type MIN_LENGTH, input the required minimum length as an integer.

          For type MAX_LENGTH, input the required maximum length as an integer.

          For type MIN_VALUE, input the minimum allowed value as a signed integer or decimal (eg. “0”, “-1”, “25.6”, “-9.999999” etc.)

          For type MAX_VALUE, input the maximum allowed value as a signed integer or decimal.

          For type INPUT_CASE, input 0 for "LOWERCASE" or 1 for “UPPERCASE”.

          For type PRECISION, input the number of allowed decimal places as an integer (eg. “0”, “1”, or “2”)'
        type: number
        example: 25.6
securityDefinitions:
  AccessToken:
    type: apiKey
    name: accessToken
    in: header
  ErplyClientCode:
    type: apiKey
    name: clientCode
    in: header
  ErplyJWT:
    type: apiKey
    name: jwt
    in: header
  ErplySession:
    type: apiKey
    name: sessionKey
    in: header
  RequestKey:
    type: apiKey
    name: requestKey
    in: header
