openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM External IDs API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: External IDs
paths:
  /v1/external-ids:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'Currently supported entities: category'
      tags:
      - External IDs
      summary: Read external IDs
      parameters:
      - description: up to 100 external IDs
        name: externalIds
        in: query
        schema:
          type: array
          items:
            type: string
      - description: up to 100 object IDs
        name: objIds
        in: query
        schema:
          type: array
          items:
            type: string
      - description: 'Entity name to filter by (currently supported: category)'
        name: entityName
        in: query
        required: true
        schema:
          type: string
      - description: integration name
        name: integrationName
        in: query
        required: true
        schema:
          type: string
      - description: skip n records
        name: skip
        in: query
        schema:
          type: integer
      - description: 'items to take, default: 20, max: 100000'
        name: take
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/models.ExternalIDResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: getV1ExternalIds
      x-operation-id-source: derived
  /v1/external-ids/{entityName}/{objIds}:
    delete:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'Currently supported entities: category'
      tags:
      - External IDs
      summary: Delete external IDs of entities
      parameters:
      - description: Specify the integration name to delete the external ID associated with the integration only.
        name: integrationName
        in: query
        required: true
        schema:
          type: string
      - description: 'Entity name (currently supported: category)'
        name: entityName
        in: path
        required: true
        schema:
          type: string
      - description: up to 100 semicolon delimited ids
        name: objIds
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: deleteV1ExternalIdsByEntityNameByObjIds
      x-operation-id-source: derived
  /v1/external-ids/{entityName}/{objId}:
    patch:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'Currently supported entities: category'
      tags:
      - External IDs
      summary: Update external ID of an entity
      parameters:
      - description: 'Entity name (currently supported: category)'
        name: entityName
        in: path
        required: true
        schema:
          type: string
      - description: Object ID
        name: objId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.ExternalIDPatchRequest'
        description: request
        required: true
      operationId: patchV1ExternalIdsByEntityNameByObjId
      x-operation-id-source: derived
  /v1/external-ids/{objId}:
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'Currently supported entities: category'
      tags:
      - External IDs
      summary: Attach external ID to an entity
      parameters:
      - description: Object ID
        name: objId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.ExternalIDPatchRequest'
        description: request
        required: true
      operationId: postV1ExternalIdsByObjId
      x-operation-id-source: derived
components:
  schemas:
    models.ExternalIDPatchRequest:
      type: object
      properties:
        external_id:
          type: string
        integration_name:
          type: string
    responses.Response:
      type: object
      properties:
        id:
          type: integer
          example: 73
    models.ExternalIDResponse:
      type: object
      properties:
        added:
          description: Unix timestamp
          type: integer
          example: 1595230999
        addedby_id:
          description: user ID
          type: integer
          example: 1
        changed:
          description: Unix timestamp
          type: integer
          example: 1595230999
        changedby_id:
          description: user ID
          type: integer
          example: 1
        entityName:
          type: string
        external_id:
          type: string
        integration_name:
          type: string
        obj_id:
          type: integer
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
