openapi: 3.2.0
info:
  description: '## Overview


    This application offers an API for managing assignments and tasks.'
  title: assignments Clsf Labels API
  contact: {}
  version: 2.36.5
tags:
- name: clsf-labels
paths:
  /api/v1/clsf/label:
    get:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-labels
      summary: Look up labels
      parameters:
      - description: Object type for which labels should be returned. One of [workorder raji]
        name: entity
        in: query
        required: true
        schema:
          type: string
      - description: Label type code for which labels should be returned
        name: labelType
        in: query
        schema:
          type: string
      - description: Label ids
        name: ids
        in: query
        style: form
        explode: false
        schema:
          type: array
          items:
            type: integer
      - description: Language to use when sorting by name (`en`, `et`, `ru` etc.)
        name: lang
        in: query
        schema:
          type: string
      - description: Label code to search for. Partial matching from the beginning of the code
        name: code
        in: query
        schema:
          type: string
      - description: Result page size
        name: pageSize
        in: query
        schema:
          type: integer
      - description: Result page number
        name: pageNr
        in: query
        schema:
          type: integer
      - description: 'Sorting order. Supported values are: `id`, `name`. Defaults to `id`'
        name: sort
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClsfResponse'
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: getApiV1ClsfLabel
      x-operation-id-source: derived
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-labels
      summary: Add a new label record
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClsfLabelRequest'
        description: Label record
        required: true
      operationId: postApiV1ClsfLabel
      x-operation-id-source: derived
  /api/v1/clsf/label-type:
    get:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-labels
      summary: Look up label types
      parameters:
      - description: Label type ids
        name: ids
        in: query
        style: form
        explode: false
        schema:
          type: array
          items:
            type: integer
      - description: Object type for which label types should be returned. One of [workorder raji]
        name: entity
        in: query
        required: true
        schema:
          type: string
      - description: Language to use when sorting by name (`en`, `et`, `ru` etc.)
        name: lang
        in: query
        schema:
          type: string
      - description: Label type code to search for. Partial matching from the beginning of the code
        name: code
        in: query
        schema:
          type: string
      - description: Result page size
        name: pageSize
        in: query
        schema:
          type: integer
      - description: Result page number
        name: pageNr
        in: query
        schema:
          type: integer
      - description: 'Sorting order. Supported values are: `id`, `name`. Defaults to `id`'
        name: sort
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClsfResponse'
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: getApiV1ClsfLabelType
      x-operation-id-source: derived
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-labels
      summary: Add a new label type
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClsfLabelTypeRequest'
        description: Clsf record
        required: true
      operationId: postApiV1ClsfLabelType
      x-operation-id-source: derived
  /api/v1/clsf/label-type/{typeId}:
    delete:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-labels
      summary: Delete one label type record
      parameters:
      - description: Record id
        name: typeId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: deleteApiV1ClsfLabelTypeByTypeId
      x-operation-id-source: derived
    patch:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-labels
      summary: Update an existing label type record
      parameters:
      - description: Record id
        name: typeId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClsfLabelTypeRequest'
        description: Clsf record
        required: true
      operationId: patchApiV1ClsfLabelTypeByTypeId
      x-operation-id-source: derived
  /api/v1/clsf/label/{labelId}:
    delete:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-labels
      summary: Delete one label record
      parameters:
      - description: Record id
        name: labelId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: deleteApiV1ClsfLabelByLabelId
      x-operation-id-source: derived
    patch:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      tags:
      - clsf-labels
      summary: Update an existing label record
      parameters:
      - description: Record id
        name: labelId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClsfResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClsfLabelRequest'
        description: Clsf record
        required: true
      operationId: patchApiV1ClsfLabelByLabelId
      x-operation-id-source: derived
components:
  schemas:
    ClsfLabelRequest:
      type: object
      properties:
        code:
          type: string
        entity:
          type: string
        id:
          type: integer
        name:
          $ref: '#/components/schemas/core.Translatable'
        type:
          type: string
    ClsfLabelTypeRequest:
      type: object
      properties:
        code:
          type: string
        entity:
          type: string
        id:
          type: integer
        name:
          $ref: '#/components/schemas/core.Translatable'
    ClsfChildResponse:
      type: object
      properties:
        code:
          type: string
        type:
          type: string
    core.Translatable:
      type: object
      properties:
        ar:
          type: string
          example: ' '
        cs:
          type: string
          example: ' '
        da:
          type: string
          example: ' '
        de:
          type: string
          example: ' '
        default:
          type: string
          example: ' '
        el:
          type: string
          example: ' '
        en:
          type: string
          example: ' '
        es:
          type: string
          example: ' '
        et:
          type: string
          example: ' '
        fi:
          type: string
          example: ' '
        fo:
          type: string
          example: ' '
        fr:
          type: string
          example: ' '
        it:
          type: string
          example: ' '
        lt:
          type: string
          example: ' '
        lv:
          type: string
          example: ' '
        nl:
          type: string
          example: ' '
        'no':
          type: string
          example: ' '
        pl:
          type: string
          example: ' '
        ru:
          type: string
          example: ' '
        sv:
          type: string
          example: ' '
        th:
          type: string
          example: ' '
        tr:
          type: string
          example: ' '
        vi:
          type: string
          example: ' '
        zh_Hans:
          type: string
          example: ' '
        zh_Hant:
          type: string
          example: ' '
    ClsfResponse:
      type: object
      properties:
        children:
          type: array
          items:
            $ref: '#/components/schemas/ClsfChildResponse'
        code:
          type: string
        createdAt:
          type: string
        createdById:
          type: integer
        entity:
          type: string
        id:
          type: integer
        name:
          $ref: '#/components/schemas/core.Translatable'
        parentId:
          type: integer
        updatedAt:
          type: string
        updatedById:
          type: integer
  securitySchemes:
    AccessToken:
      type: apiKey
      name: accessToken
      in: header
    ErplyClientCode:
      type: apiKey
      name: clientCode
      in: header
    ErplyJWT:
      type: apiKey
      name: jwt
      in: header
    ErplySession:
      type: apiKey
      name: sessionKey
      in: header
    RequestKey:
      type: apiKey
      name: requestKey
      in: header
