openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM Product Fields API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: Product Fields
paths:
  /v1/product/fields/inherited:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: There is an option to make matrix variations inherit specific field values from their parent product.
      tags:
      - Product Fields
      summary: Read product fields that will be inherited from matrix products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: getV1ProductFieldsInherited
      x-operation-id-source: derived
    patch:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'There is an option to make matrix variations inherit specific field values from their parent product.


        This setting is followed when editing matrix products. The variation fields will be overwritten automatically.


        Set field values for the fields you want to (re)configure only.'
      tags:
      - Product Fields
      summary: Set product fields that will be inherited from matrix products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/products.ProductInheritedFieldsRequest'
        description: request
        required: true
      operationId: patchV1ProductFieldsInherited
      x-operation-id-source: derived
  /v1/product/fields/permissions:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Read view, edit, add, delete permissions for product fields.
      tags:
      - Product Fields
      summary: Read permissions for product fields
      parameters:
      - description: user group ID
        name: userGroupID
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/products.ProductFieldsPermissions'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: getV1ProductFieldsPermissions
      x-operation-id-source: derived
    patch:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'Set view, edit, add, delete permissions for product fields.


        Set field values for the fields you want to (re)configure only.'
      tags:
      - Product Fields
      summary: Set permissions for product fields, permissions are user group based
      parameters:
      - description: user group ID
        name: userGroupID
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/products.ProductFieldsPermissions'
        description: request
        required: true
      operationId: patchV1ProductFieldsPermissions
      x-operation-id-source: derived
components:
  schemas:
    products.ProductInheritedFieldsRequest:
      type: object
      properties:
        age_restriction:
          type: boolean
        alcohol_percentage:
          type: boolean
        alcohol_registry_number:
          type: boolean
        batches:
          type: boolean
        brand_id:
          description: ID of product brand. To get the list of brandmodels, use getBrands.
          type: boolean
        cashier_must_enter_price:
          description: boolean flag 0 or 1
          type: boolean
        category_id:
          type: boolean
        code:
          description: Product's code. Must be UNIQUE, unless the account is configured otherwise.
          type: boolean
        code2:
          type: boolean
        code3:
          description: Third code of the item (note that this field may not be visible on product card by default).
          type: boolean
        code5:
          type: boolean
        code6:
          type: boolean
        code7:
          type: boolean
        code8:
          type: boolean
        cost:
          description: Cost is Product cost
          type: boolean
        country_of_origin_id:
          type: boolean
        delivery_time:
          type: boolean
        deposit_fee_amount:
          type: boolean
        deposit_fee_id:
          description: ContainerID is ID of another product, a beverage container that is always sold together with this item.
          type: boolean
        description:
          description: '//PlainTextDescription is translatable plain text description

            PlainTextDescription map[string]string `json:"plain_text_description"`

            //HTMLDescription is translatable html description

            HTMLDescription map[string]string `json:"html_description"`

            Description is translatable and of 2 types: plain text, HTML. Languages should be in ISO 639-1 Code'
          type: boolean
        displayed_in_webshop:
          description: 0 or 1
          type: boolean
        excise_declaration_number:
          type: boolean
        extra_field1_id:
          type: boolean
        extra_field2_id:
          type: boolean
        extra_field3_id:
          type: boolean
        extra_field4_id:
          type: boolean
        family_id:
          type: boolean
        gross_weight:
          description: GrossWeight is Item's gross weight (with packaging). Unit depends on region, check your Erply account (typically lbs or kg).
          type: boolean
        group_id:
          description: ID of product group. To get the list of product groups, use getProductGroups.
          type: boolean
        has_serial_numbers:
          type: boolean
        height:
          type: boolean
        is_gift_card:
          description: 0 or 1
          type: boolean
        is_regular_gift_card:
          description: boolean flag 0 or 1
          type: boolean
        labels_not_needed:
          description: boolean flag 0 or 1
          type: boolean
        length:
          description: Length is Item's physical dimensions.
          type: boolean
        location_in_warehouse_id:
          description: LocationInWarehouseID is ID of selected location in warehouse.
          type: boolean
        location_in_warehouse_text:
          description: LocationInWarehouseText is Product's specific text added to location in warehouse.
          type: boolean
        manufacturer_name:
          type: boolean
        name:
          type: boolean
        net_weight:
          description: NetWeight is Item's net weight. Unit depends on region, check your Erply account (typically lbs or kg).
          type: boolean
        non_discountable:
          description: 0 or 1
          type: boolean
        non_refundable:
          description: 0 or 1
          type: boolean
        non_stock_product:
          description: boolean flag 0 or 1
          type: boolean
        packaging_type:
          type: boolean
        packing_not_required:
          type: boolean
        price:
          description: 'Price is just the default price of a product and the actual price applied in a particular location, to a particular customer, depends on price lists and promotions: https://learn-api.erply.com/concepts/pricing'
          type: boolean
        price_with_tax:
          type: boolean
        priority_group_id:
          type: boolean
        product_reorder_multiples:
          type: boolean
        reward_points_not_allowed:
          description: boolean flag 0 or 1
          type: boolean
        sold_in_packages:
          type: boolean
        status:
          type: boolean
        suggested_retail_price:
          type: boolean
        supplier_code:
          description: Supplier's product code
          type: boolean
        supplier_id:
          type: boolean
        supplier_name:
          type: boolean
        tax_free:
          description: boolean flag 0 or 1
          type: boolean
        tax_rate_id:
          description: 'TaxRateID is just the default tax rate of a product and the actual tax applied in a particular location depends on multiple rules: https://learn-api.erply.com/concepts/taxes.'
          type: boolean
        type:
          type: boolean
        unit_id:
          description: ID of product unit. To get the list of units, use getProductUnits.
          type: boolean
        volume:
          description: Volume is Item's fluid volume, eg. for beverages or perfumery. Unit depends on locale, check your Erply account (typically mL or fl oz).
          type: boolean
        width:
          type: boolean
    responses.Response:
      type: object
      properties:
        id:
          type: integer
          example: 73
    products.ProductFieldsPermissions:
      type: object
      properties:
        age_restriction:
          $ref: '#/components/schemas/products.PermissionSet'
        alcohol_percentage:
          $ref: '#/components/schemas/products.PermissionSet'
        alcohol_registry_number:
          $ref: '#/components/schemas/products.PermissionSet'
        batches:
          $ref: '#/components/schemas/products.PermissionSet'
        brand_id:
          description: ID of product brand. To get the list of brandmodels, use getBrands.
          $ref: '#/components/schemas/products.PermissionSet'
        cashier_must_enter_price:
          description: boolean flag 0 or 1
          $ref: '#/components/schemas/products.PermissionSet'
        category_id:
          $ref: '#/components/schemas/products.PermissionSet'
        code:
          description: Product's code. Must be UNIQUE, unless the account is configured otherwise.
          $ref: '#/components/schemas/products.PermissionSet'
        code2:
          $ref: '#/components/schemas/products.PermissionSet'
        code3:
          description: Third code of the item (note that this field may not be visible on product card by default).
          $ref: '#/components/schemas/products.PermissionSet'
        code5:
          $ref: '#/components/schemas/products.PermissionSet'
        code6:
          $ref: '#/components/schemas/products.PermissionSet'
        code7:
          $ref: '#/components/schemas/products.PermissionSet'
        code8:
          $ref: '#/components/schemas/products.PermissionSet'
        cost:
          description: Cost is Product cost
          $ref: '#/components/schemas/products.PermissionSet'
        country_of_origin_id:
          $ref: '#/components/schemas/products.PermissionSet'
        delivery_time:
          $ref: '#/components/schemas/products.PermissionSet'
        deposit_fee_amount:
          $ref: '#/components/schemas/products.PermissionSet'
        deposit_fee_id:
          description: ContainerID is ID of another product, a beverage container that is always sold together with this item.
          $ref: '#/components/schemas/products.PermissionSet'
        description:
          description: '//PlainTextDescription is translatable plain text description

            PlainTextDescription map[string]string `json:"plain_text_description,omitempty"`

            //HTMLDescription is translatable html description

            HTMLDescription map[string]string `json:"html_description,omitempty"`

            Description is translatable and of 2 types: plain text, HTML. Languages should be in ISO 639-1 Code'
          $ref: '#/components/schemas/products.PermissionSet'
        displayed_in_webshop:
          description: 0 or 1
          $ref: '#/components/schemas/products.PermissionSet'
        excise_declaration_number:
          $ref: '#/components/schemas/products.PermissionSet'
        extra_field1_id:
          $ref: '#/components/schemas/products.PermissionSet'
        extra_field2_id:
          $ref: '#/components/schemas/products.PermissionSet'
        extra_field3_id:
          $ref: '#/components/schemas/products.PermissionSet'
        extra_field4_id:
          $ref: '#/components/schemas/products.PermissionSet'
        family_id:
          $ref: '#/components/schemas/products.PermissionSet'
        gross_weight:
          description: GrossWeight is Item's gross weight (with packaging). Unit depends on region, check your Erply account (typically lbs or kg).
          $ref: '#/components/schemas/products.PermissionSet'
        group_id:
          description: ID of product group. To get the list of product groups, use getProductGroups.
          $ref: '#/components/schemas/products.PermissionSet'
        has_serial_numbers:
          $ref: '#/components/schemas/products.PermissionSet'
        height:
          $ref: '#/components/schemas/products.PermissionSet'
        is_gift_card:
          description: 0 or 1
          $ref: '#/components/schemas/products.PermissionSet'
        is_regular_gift_card:
          description: boolean flag 0 or 1
          $ref: '#/components/schemas/products.PermissionSet'
        labels_not_needed:
          description: boolean flag 0 or 1
          $ref: '#/components/schemas/products.PermissionSet'
        length:
          description: Length is Item's physical dimensions.
          $ref: '#/components/schemas/products.PermissionSet'
        location_in_warehouse_id:
          description: LocationInWarehouseID is ID of selected location in warehouse.
          $ref: '#/components/schemas/products.PermissionSet'
        location_in_warehouse_text:
          description: LocationInWarehouseText is Product's specific text added to location in warehouse.
          $ref: '#/components/schemas/products.PermissionSet'
        manufacturer_name:
          $ref: '#/components/schemas/products.PermissionSet'
        name:
          $ref: '#/components/schemas/products.PermissionSet'
        net_weight:
          description: NetWeight is Item's net weight. Unit depends on region, check your Erply account (typically lbs or kg).
          $ref: '#/components/schemas/products.PermissionSet'
        non_discountable:
          description: 0 or 1
          $ref: '#/components/schemas/products.PermissionSet'
        non_refundable:
          description: 0 or 1
          $ref: '#/components/schemas/products.PermissionSet'
        non_stock_product:
          description: boolean flag 0 or 1
          $ref: '#/components/schemas/products.PermissionSet'
        packaging_type:
          $ref: '#/components/schemas/products.PermissionSet'
        packing_not_required:
          $ref: '#/components/schemas/products.PermissionSet'
        price:
          description: 'Price is just the default price of a product and the actual price applied in a particular location, to a particular customer, depends on price lists and promotions: https://learn-api.erply.com/concepts/pricing'
          $ref: '#/components/schemas/products.PermissionSet'
        price_with_tax:
          $ref: '#/components/schemas/products.PermissionSet'
        priority_group_id:
          $ref: '#/components/schemas/products.PermissionSet'
        product_reorder_multiples:
          $ref: '#/components/schemas/products.PermissionSet'
        reward_points_not_allowed:
          description: boolean flag 0 or 1
          $ref: '#/components/schemas/products.PermissionSet'
        sold_in_packages:
          $ref: '#/components/schemas/products.PermissionSet'
        status:
          $ref: '#/components/schemas/products.PermissionSet'
        suggested_retail_price:
          $ref: '#/components/schemas/products.PermissionSet'
        supplier_code:
          description: Supplier's product code
          $ref: '#/components/schemas/products.PermissionSet'
        supplier_id:
          $ref: '#/components/schemas/products.PermissionSet'
        supplier_name:
          $ref: '#/components/schemas/products.PermissionSet'
        tax_free:
          description: boolean flag 0 or 1
          $ref: '#/components/schemas/products.PermissionSet'
        tax_rate_id:
          description: 'TaxRateID is just the default tax rate of a product and the actual tax applied in a particular location depends on multiple rules: https://learn-api.erply.com/concepts/taxes.'
          $ref: '#/components/schemas/products.PermissionSet'
        type:
          $ref: '#/components/schemas/products.PermissionSet'
        unit_id:
          description: ID of product unit. To get the list of units, use getProductUnits.
          $ref: '#/components/schemas/products.PermissionSet'
        volume:
          description: Volume is Item's fluid volume, eg. for beverages or perfumery. Unit depends on locale, check your Erply account (typically mL or fl oz).
          $ref: '#/components/schemas/products.PermissionSet'
        width:
          $ref: '#/components/schemas/products.PermissionSet'
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
    products.PermissionSet:
      type: object
      properties:
        edit:
          type: boolean
        view:
          type: boolean
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
