openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM Product Family API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: Product Family
paths:
  /v1/product/family:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Get Product Family
      tags:
      - Product Family
      summary: Get Families
      parameters:
      - description: show archived families?
        name: withArchived
        in: query
        required: true
        schema:
          type: boolean
      - description: skip n records
        name: skip
        in: query
        schema:
          type: integer
      - description: 'items to take, default: 20, max: 100000'
        name: take
        in: query
        schema:
          type: integer
      - description: the sort parameter is explained in the `Filtering & Sorting` section on top of the Swagger documentation
        name: sort
        in: query
        schema:
          type: string
      - description: the filter parameter is explained in the `Filtering & Sorting` section on top of the Swagger documentation
        name: filter
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/familymodels.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: getV1ProductFamily
      x-operation-id-source: derived
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Create Product Family
      tags:
      - Product Family
      summary: Create Family
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requests.Archivable'
        description: Name
        required: true
      operationId: postV1ProductFamily
      x-operation-id-source: derived
  /v1/product/family/bulk:
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: each request contains the created resource data
      tags:
      - Product Family
      summary: Create families in bulk
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.BulkResponseWithResults'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/familymodels.BulkCreateRequest'
        description: bulk create request
        required: true
      operationId: postV1ProductFamilyBulk
      x-operation-id-source: derived
  /v1/product/family/bulk/get:
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Product Family
      summary: Get families in bulk
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/familymodels.BulkReadResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/familymodels.BulkReadRequest'
        description: requests have the parameters that the original get request has, but in json format. This way you can apply the parameters to each request separately.
        required: true
      operationId: postV1ProductFamilyBulkGet
      x-operation-id-source: derived
  /v1/product/family/{id}:
    put:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: By updating a product family you can "delete" it by archiving
      tags:
      - Product Family
      summary: Update Family
      parameters:
      - description: family ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requests.Archivable'
        description: Name
        required: true
      operationId: putV1ProductFamilyById
      x-operation-id-source: derived
components:
  schemas:
    familymodels.BulkReadResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/familymodels.BulkReadResponseItem'
    familymodels.ReadRequest:
      type: object
      properties:
        filters:
          type: array
          items:
            $ref: '#/components/schemas/parammodels.FilterJSON'
        paginationParameters:
          $ref: '#/components/schemas/parammodels.PaginationParameters'
        sortingParameters:
          $ref: '#/components/schemas/parammodels.SortRequest'
        withArchived:
          type: boolean
    familymodels.BulkCreateRequest:
      type: object
      properties:
        requests:
          type: array
          items:
            $ref: '#/components/schemas/requests.Archivable'
    parammodels.SortRequest:
      type: object
      properties:
        desc:
          description: If true - descending, if false - ascending
          type: boolean
        language:
          description: Language in ISO 639-1 standard. Is needed only for translatable properties like description and name.
          type: string
          example: en
        selector:
          description: 'JSON field. For description: description_plain or description_html'
          type: string
          example: name
    familymodels.Response:
      type: object
      properties:
        added:
          description: Unix timestamp
          type: integer
          example: 1595230999
        addedby_id:
          description: user ID
          type: integer
          example: 1
        archived:
          type: integer
        changed:
          description: Unix timestamp
          type: integer
          example: 1595230999
        changedby_id:
          description: user ID
          type: integer
          example: 1
        id:
          type: integer
        name:
          description: /This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          $ref: '#/components/schemas/Translatable'
    responses.BulkResult:
      type: object
      properties:
        message:
          type: string
          example: some message
        resourceId:
          description: identifier of the REST-ful response
          type: integer
          example: 2
        resultId:
          description: identifier of the result item
          type: integer
          example: 2
    responses.Response:
      type: object
      properties:
        id:
          type: integer
          example: 73
    familymodels.BulkReadRequest:
      type: object
      properties:
        requests:
          type: array
          items:
            $ref: '#/components/schemas/familymodels.ReadRequest'
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
    parammodels.FilterJSON:
      type: object
      properties:
        fieldName:
          type: string
          example: group_id
        operandBefore:
          description: supported values are "and", "or"
          type: string
          example: or
        operator:
          type: string
          example: '='
        sliceValue:
          description: to be used if the value is a slice
          type: array
          items: {}
        value:
          type: object
    familymodels.BulkReadResponseItem:
      type: object
      properties:
        families:
          type: array
          items:
            $ref: '#/components/schemas/familymodels.Response'
        message:
          type: string
          example: some message
        resultId:
          description: id of the response, if requested 3 read requests each ID represents 1 response item
          type: integer
    parammodels.PaginationParameters:
      type: object
      properties:
        skip:
          type: integer
        take:
          type: integer
    Translatable:
      type: object
      properties:
        en:
          description: This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          type: string
    responses.BulkResponseWithResults:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/responses.BulkResult'
    requests.Archivable:
      type: object
      properties:
        archived:
          description: Archived ..
          type: boolean
          example: false
        name:
          description: Names translations
          $ref: '#/components/schemas/Translatable'
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
