openapi: 3.2.0
info:
  description: '## Overview


    This application offers an API for managing assignments and tasks.'
  title: assignments Form API
  contact: {}
  version: 2.36.5
tags:
- name: Form
paths:
  /api/v1/form/registration:
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      tags:
      - Form
      summary: Submit a registration form
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationFormRequest'
        description: Registration data
        required: true
      operationId: postApiV1FormRegistration
      x-operation-id-source: derived
components:
  schemas:
    RegistrationFormRequest:
      type: object
      properties:
        brand:
          type: string
        data:
          type: object
        email:
          type: string
        firstname:
          type: string
        model:
          type: string
        name:
          type: string
        phone:
          type: string
        registration:
          type: string
        serviceName:
          type: string
        year:
          type: string
  securitySchemes:
    AccessToken:
      type: apiKey
      name: accessToken
      in: header
    ErplyClientCode:
      type: apiKey
      name: clientCode
      in: header
    ErplyJWT:
      type: apiKey
      name: jwt
      in: header
    ErplySession:
      type: apiKey
      name: sessionKey
      in: header
    RequestKey:
      type: apiKey
      name: requestKey
      in: header
