openapi: 3.2.0
info:
  description: API endpoints to manager webhook configurations. In order to start receiving the webhooks you need to configure the specific events using this API.
  title: Webhook Manager Webhook Configuration API
  contact: {}
  version: v1.18.3
tags:
- name: Webhook Configuration
paths:
  /v1/webhook-configuration:
    get:
      security:
      - ClientCode: []
      - SessionKey: []
      description: '# Get webhook configurations

        Get current authenticated users existing webhook configurations'
      tags:
      - Webhook Configuration
      summary: Get webhook configurations
      operationId: getWebhookConfigurations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/models.WebhookConfiguration'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.OutputError'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.OutputError'
    post:
      security:
      - ClientCode: []
      - SessionKey: []
      description: '# Add new webhook configuration

        In action field use: insert, update, delete or confirm (only usable on items that support it)'
      tags:
      - Webhook Configuration
      summary: Add webhook configuration
      operationId: addWebhookConfiguration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.WebhookConfiguration'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.OutputError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.OutputError'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.OutputError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.InputWebhookConfiguration'
        description: New webhook configuration data
        required: true
  /v1/webhook-configuration/{id}:
    put:
      security:
      - ClientCode: []
      - SessionKey: []
      description: '# Update existing webhook configuration

        Updates an existing webhook configuration by its id'
      tags:
      - Webhook Configuration
      summary: Update existing webhook configuration
      operationId: updateWebhookConfiguration
      parameters:
      - description: ID of the webhook configuration
        name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.WebhookConfiguration'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.OutputError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.OutputError'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.OutputError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.InputWebhookConfiguration'
        description: Edit webhook configuration data
        required: true
    delete:
      security:
      - ClientCode: []
      - SessionKey: []
      description: '# Remove existing webhook configuration

        Removes an existing webhook configuration by its id'
      tags:
      - Webhook Configuration
      summary: Remove existing webhook configuration
      operationId: removeWebhookConfiguration
      parameters:
      - description: ID of the webhook configuration
        name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.OutputOK'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.OutputError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.OutputError'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.OutputError'
components:
  schemas:
    models.OutputOK:
      type: object
      properties:
        message:
          type: string
          example: configuration removed
    models.OutputError:
      type: object
      properties:
        error:
          type: string
          example: Description of the failure
    models.InputWebhookConfiguration:
      type: object
      required:
      - action
      - endpoint
      - secret
      - table
      properties:
        action:
          description: Action of the event insert, update, delete or confirm (only usable on items that support it)
          type: string
          example: insert
        disabled:
          description: Disabled optional input, can be used to create inactive configurations for later use - false by default
          type: boolean
          example: false
        endpoint:
          description: Endpoint full url of the server where the webhook will be sent to
          type: string
          example: https://my.receiver
        secret:
          description: Secret optional secret that can be used to authenticate the webhooks
          type: string
          example: mySecretWord
        table:
          description: Table references a database table or a custom event name
          type: string
          example: product
    models.WebhookConfiguration:
      type: object
      properties:
        action:
          type: string
          example: insert
        clientcode:
          type: string
          example: '000000'
        createdat:
          type: string
          example: '2019-11-21T14:01:13.471Z'
        disabled:
          type: boolean
          example: false
        endpoint:
          type: string
          example: https://test.receiver
        id:
          type: string
          example: 5dd63cc81810fd18722e23df
        secret:
          type: string
          example: mySecretWord
        table:
          type: string
          example: product
        updatedat:
          type: string
          example: '2019-11-21T14:01:13.471Z'
  securitySchemes:
    ClientCode:
      type: apiKey
      name: clientCode
      in: header
    SessionKey:
      type: apiKey
      name: sessionKey
      in: header
