openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM Permissions API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: Permissions
paths:
  /v1/permissions:
    patch:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: 'Some entities support setting up permissions on the user level. They include product groups and categpries.

        Response is the userID of the updated user'
      tags:
      - Permissions
      summary: Set / Update a permission
      parameters:
      - description: 'values: ''product group'' or ''product category'''
        name: entity
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/permissions.SetUserPermissionRequest'
        description: request
        required: true
      operationId: patchV1Permissions
      x-operation-id-source: derived
  /v1/permissions/{userID}:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      tags:
      - Permissions
      summary: Get user permissions
      parameters:
      - description: user ID
        name: userID
        in: path
        schema:
          type: integer
        required: true
      - description: 'values: ''product group'' or ''product category'''
        name: entity
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers:
            X-Total-Count:
              description: total number of records (ignores skip & take parameters)
              schema:
                type: uint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/permissions.UserPermission'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: getV1PermissionsByUserID
      x-operation-id-source: derived
components:
  schemas:
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
    responses.Response:
      type: object
      properties:
        id:
          type: integer
          example: 73
    permissions.SetUserPermissionRequest:
      type: object
      properties:
        isCreateEnabled:
          type: boolean
        isDeleteEnabled:
          type: boolean
        isUpdateEnabled:
          type: boolean
        userID:
          type: integer
    permissions.UserPermission:
      type: object
      properties:
        isCreateEnabled:
          type: boolean
        isDeleteEnabled:
          type: boolean
        isUpdateEnabled:
          type: boolean
        userID:
          type: integer
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
