openapi: 3.2.0
info:
  description: 'Product information management API

    -------


    Summary


    It is built top of Erply''s current product database.'
  title: PIM Product Parameter Set API
  contact:
    email: david.zingerman@erply.com
  version: 1.143.20
tags:
- name: Product Parameter Set
paths:
  /v1/product/parameter/set:
    get:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Get Product Parameter Sets
      tags:
      - Product Parameter Set
      summary: Get Parameter Sets
      parameters:
      - description: skip n records
        name: skip
        in: query
        schema:
          type: integer
      - description: 'items to take, default: 20, max: 100000'
        name: take
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/models.SetResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: getV1ProductParameterSet
      x-operation-id-source: derived
    post:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Create Product Parameter Set
      tags:
      - Product Parameter Set
      summary: Create Parameter Set
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requests.Request'
        description: Name
        required: true
      operationId: postV1ProductParameterSet
      x-operation-id-source: derived
  /v1/product/parameter/set/{ids}:
    delete:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Deleting a Product Parameter Set will also delete its parameters options and values
      tags:
      - Product Parameter Set
      summary: Delete Parameter Sets
      parameters:
      - description: up to 100 semicolon delimited set IDs
        name: ids
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      operationId: deleteV1ProductParameterSetByIds
      x-operation-id-source: derived
  /v1/product/parameter/set/{id}:
    put:
      security:
      - sk: []
      - cc: []
      - jwt: []
      description: Update Product Parameter Set
      tags:
      - Product Parameter Set
      summary: Update Set's Name
      parameters:
      - description: set ID
        name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses.MessageResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requests.Request'
        description: Name
        required: true
      operationId: putV1ProductParameterSetById
      x-operation-id-source: derived
components:
  schemas:
    Translatable:
      type: object
      properties:
        en:
          description: This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          type: string
    responses.MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: some message
    requests.Request:
      type: object
      properties:
        name:
          description: Names translations
          $ref: '#/components/schemas/Translatable'
    models.SetResponse:
      type: object
      properties:
        added:
          description: Unix timestamp
          type: integer
          example: 1595230999
        addedby_id:
          description: user ID
          type: integer
          example: 1
        changed:
          description: Unix timestamp
          type: integer
          example: 1595230999
        changedby_id:
          description: user ID
          type: integer
          example: 1
        id:
          type: integer
        name:
          description: /This field supports more languages. Please read Translatable names and descriptions block in the documentation.
          $ref: '#/components/schemas/Translatable'
    responses.Response:
      type: object
      properties:
        id:
          type: integer
          example: 73
  securitySchemes:
    cc:
      type: apiKey
      name: clientCode
      in: header
    jwt:
      type: apiKey
      name: jwt
      in: header
    sk:
      type: apiKey
      name: sessionKey
      in: header
