openapi: 3.2.0
info:
  description: '## Overview


    This application offers an API for managing assignments and tasks.'
  title: assignments Item API
  contact: {}
  version: 2.36.5
tags:
- name: Item
paths:
  /api/v1/workorder/{workorderId}/item:
    get:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      description: 'Allows searching for workorder items matching specific criteria.


        > Param | Default | Example | Description

        > ----------------|---------|---------|----

        > `withTotalCount` | false | true | If total count of matched records should be returned in response header `x-total-count

        > `pageSize` | 20 | 100 | Allows specifying how many records per page should be returned

        > `pageNr` | 1 | 2 | Allows specifying which page should be returned for creating paginated views over the data.

        > `sort` | id | -id | Allows specifying in which order the rows should be returned. Supported values are: `id`. It is possible to reverse the order by adding a `-` prefix to the sorting keyword.

        >

        >'
      tags:
      - Item
      summary: Look up items
      parameters:
      - description: Workorder id
        name: workorderId
        in: path
        required: true
        schema:
          type: integer
      - description: If total matching record count should be return in response header
        name: withTotalCount
        in: query
        schema:
          type: boolean
      - description: Result page size
        name: pageSize
        in: query
        schema:
          type: integer
      - description: Result page number
        name: pageNr
        in: query
        schema:
          type: integer
      - description: Sorting order
        name: sort
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ItemResponse'
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: getApiV1WorkorderByWorkorderIdItem
      x-operation-id-source: derived
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      tags:
      - Item
      summary: Add a new item record
      parameters:
      - description: Workorder id
        name: workorderId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemRequest'
        description: Item record
        required: true
      operationId: postApiV1WorkorderByWorkorderIdItem
      x-operation-id-source: derived
  /api/v1/workorder/{workorderId}/item/{itemId}:
    delete:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      tags:
      - Item
      summary: Delete one item record
      parameters:
      - description: Workorder id
        name: workorderId
        in: path
        required: true
        schema:
          type: integer
      - description: Record id
        name: itemId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: deleteApiV1WorkorderByWorkorderIdItemByItemId
      x-operation-id-source: derived
    patch:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      tags:
      - Item
      summary: Update item record
      parameters:
      - description: Workorder id
        name: workorderId
        in: path
        required: true
        schema:
          type: integer
      - description: Record id
        name: itemId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemRequest'
        description: Item record
        required: true
      operationId: patchApiV1WorkorderByWorkorderIdItemByItemId
      x-operation-id-source: derived
  /api/v1/workorder/{workorderId}/item/{itemId}/link:
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      description: One or more rows in the same workorder and item can now be linked together. This is supported only for services, not regular products. Linked rows will be associated with the same task as a group and will share their state - performing task related or state change actions on one row will affect all of them.
      tags:
      - Item
      summary: Link rows together
      parameters:
      - description: Workorder id
        name: workorderId
        in: path
        required: true
        schema:
          type: integer
      - description: Item id
        name: itemId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RowLinkRequest'
        description: Link payload
        required: true
      operationId: postApiV1WorkorderByWorkorderIdItemByItemIdLink
      x-operation-id-source: derived
  /api/v1/workorder/{workorderId}/item/{itemId}/link/{rowId}:
    delete:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      tags:
      - Item
      summary: Unlink row from other rows
      parameters:
      - description: Workorder id
        name: workorderId
        in: path
        required: true
        schema:
          type: integer
      - description: Item id
        name: itemId
        in: path
        required: true
        schema:
          type: integer
      - description: Row id
        name: rowId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: deleteApiV1WorkorderByWorkorderIdItemByItemIdLinkByRowId
      x-operation-id-source: derived
components:
  schemas:
    ItemResponse:
      type: object
      properties:
        createdAt:
          type: string
        createdById:
          type: integer
        data:
          type: object
        id:
          type: integer
        templateId:
          type: integer
        templateSourceId:
          type: integer
        text:
          type: string
        updatedAt:
          type: string
        updatedById:
          type: integer
        workorderId:
          type: integer
    RowLinkRequest:
      type: object
      properties:
        rowIds:
          type: array
          items:
            type: integer
    ItemRequest:
      type: object
      properties:
        data:
          type: object
        id:
          type: integer
        text:
          type: string
        workorderId:
          type: integer
  securitySchemes:
    AccessToken:
      type: apiKey
      name: accessToken
      in: header
    ErplyClientCode:
      type: apiKey
      name: clientCode
      in: header
    ErplyJWT:
      type: apiKey
      name: jwt
      in: header
    ErplySession:
      type: apiKey
      name: sessionKey
      in: header
    RequestKey:
      type: apiKey
      name: requestKey
      in: header
