openapi: 3.2.0
info:
  description: '## Overview


    This application offers an API for managing assignments and tasks.'
  title: assignments Auth API
  contact: {}
  version: 2.36.5
tags:
- name: Auth
paths:
  /api/v1/auth:
    post:
      description: Returns an Erply session token which can be used for calling the authenticated endpoints. This session token is retrieved from Erply API and the authentication method is exposed here just for the convenience. During actual use the client system does not need to authenticate against this endpoint, but can retrieve the Erply session token by any means available to them
      tags:
      - Auth
      summary: Authenticate to get session token
      deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIAuthResponse'
        '400':
          description: Problematic request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APIAuthRequest'
        description: Authenticate
        required: true
      operationId: postApiV1Auth
      x-operation-id-source: derived
components:
  schemas:
    APIAuthRequest:
      type: object
      properties:
        clientCode:
          type: string
          example: '123456'
        password:
          type: string
          example: secret
        setCookie:
          type: boolean
          example: true
        username:
          type: string
          example: username
    APIAuthResponse:
      type: object
      properties:
        employeeID:
          type: string
          example: '1'
        employeeName:
          type: string
          example: Bob Smith
        sessionExpiration:
          type: integer
          example: 1661856635
        sessionKey:
          type: string
          example: d5884b1cc10b5b2f3a9601f27a21c3b57925a79fd75d
        setCookie:
          type: boolean
          example: false
        token:
          type: string
          example: jwt.token
        userID:
          type: string
          example: '1'
        userName:
          type: string
          example: username
  securitySchemes:
    AccessToken:
      type: apiKey
      name: accessToken
      in: header
    ErplyClientCode:
      type: apiKey
      name: clientCode
      in: header
    ErplyJWT:
      type: apiKey
      name: jwt
      in: header
    ErplySession:
      type: apiKey
      name: sessionKey
      in: header
    RequestKey:
      type: apiKey
      name: requestKey
      in: header
