openapi: 3.2.0
info:
  description: '## Overview


    This application offers an API for managing assignments and tasks.'
  title: assignments Resource API
  contact: {}
  version: 2.36.5
tags:
- name: Resource
paths:
  /api/v1/resource:
    get:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      tags:
      - Resource
      summary: Look up resources
      parameters:
      - description: Warehouse ID-s
        name: warehouseId
        in: query
        style: form
        explode: false
        schema:
          type: array
          items:
            type: integer
      - description: If total matching record count should be return in response header
        name: withTotalCount
        in: query
        schema:
          type: boolean
      - description: Result page size
        name: pageSize
        in: query
        schema:
          type: integer
      - description: Result page number
        name: pageNr
        in: query
        schema:
          type: integer
      - description: 'Sorting order. Supported values are: `id`, `order`'
        name: sort
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResourceResponse'
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: getApiV1Resource
      x-operation-id-source: derived
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      tags:
      - Resource
      summary: Add a new resource record
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceRequest'
        description: Resource record
        required: true
      operationId: postApiV1Resource
      x-operation-id-source: derived
  /api/v1/resource/{resourceId}:
    delete:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      tags:
      - Resource
      summary: Delete one resource record
      parameters:
      - description: Record id
        name: resourceId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: deleteApiV1ResourceByResourceId
      x-operation-id-source: derived
    patch:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      tags:
      - Resource
      summary: Update resource record
      parameters:
      - description: Record id
        name: resourceId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceResponse'
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceRequest'
        description: Resource record
        required: true
      operationId: patchApiV1ResourceByResourceId
      x-operation-id-source: derived
  /api/v1/resource/{resourceId}/order:
    post:
      security:
      - ErplyClientCode: []
      - ErplySession: []
      - ErplyJWT: []
      - AccessToken: []
      description: Allows changing the order of resources. A single record can be moved either in front of any other resource in the same warehouse, or to the end of the resource list
      tags:
      - Resource
      summary: Change the order of one resource
      parameters:
      - description: Resource id that must be moved to new position
        name: resourceId
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceOrderRequest'
        description: Reorder parameters. inFrontOfId defines the record in front of which the moved resource should be placed
        required: true
      operationId: postApiV1ResourceByResourceIdOrder
      x-operation-id-source: derived
components:
  schemas:
    ResourceRequest:
      type: object
      properties:
        code:
          type: string
        data:
          type: object
        defaultAssignedToId:
          type: integer
        id:
          type: integer
        name:
          $ref: '#/components/schemas/core.Translatable'
        warehouseId:
          type: integer
    ResourceOrderRequest:
      type: object
      properties:
        inFrontOfId:
          description: 'ID of the record in front of which the moved resource should be placed. Must belong to a record associated

            with the same warehouse. If left nil, the resource will be moved to the last place'
          type: integer
    ResourceResponse:
      type: object
      properties:
        code:
          type: string
        createdAt:
          type: string
        createdById:
          type: integer
        data:
          type: object
        defaultAssignedToId:
          type: integer
        id:
          type: integer
        name:
          $ref: '#/components/schemas/core.Translatable'
        order:
          type: integer
        updatedAt:
          type: string
        updatedById:
          type: integer
        warehouseId:
          type: integer
    core.Translatable:
      type: object
      properties:
        ar:
          type: string
          example: ' '
        cs:
          type: string
          example: ' '
        da:
          type: string
          example: ' '
        de:
          type: string
          example: ' '
        default:
          type: string
          example: ' '
        el:
          type: string
          example: ' '
        en:
          type: string
          example: ' '
        es:
          type: string
          example: ' '
        et:
          type: string
          example: ' '
        fi:
          type: string
          example: ' '
        fo:
          type: string
          example: ' '
        fr:
          type: string
          example: ' '
        it:
          type: string
          example: ' '
        lt:
          type: string
          example: ' '
        lv:
          type: string
          example: ' '
        nl:
          type: string
          example: ' '
        'no':
          type: string
          example: ' '
        pl:
          type: string
          example: ' '
        ru:
          type: string
          example: ' '
        sv:
          type: string
          example: ' '
        th:
          type: string
          example: ' '
        tr:
          type: string
          example: ' '
        vi:
          type: string
          example: ' '
        zh_Hans:
          type: string
          example: ' '
        zh_Hant:
          type: string
          example: ' '
  securitySchemes:
    AccessToken:
      type: apiKey
      name: accessToken
      in: header
    ErplyClientCode:
      type: apiKey
      name: clientCode
      in: header
    ErplyJWT:
      type: apiKey
      name: jwt
      in: header
    ErplySession:
      type: apiKey
      name: sessionKey
      in: header
    RequestKey:
      type: apiKey
      name: requestKey
      in: header
